import {
  INITIAL_ALLOCATION_CREDITS,
  KEN_LIFECYCLE_STAGES,
  LANE_OPERATING_POLICIES,
  MONTHLY_REPLENISHMENT_CREDITS,
} from "./allocation-policy.ts";
import { normalizeSearchText } from "./search-text.ts";

export const glossaryStatuses = ["operational", "sandbox", "proposed", "external"] as const;
export type GlossaryStatus = (typeof glossaryStatuses)[number];

export interface GlossaryEntry {
  id: string;
  label: string;
  plainDefinition: string;
  operationalDefinition: string;
  implementation: string[];
  governingRules: string[];
  status: GlossaryStatus;
  relatedTerms: string[];
  route: string;
  keywords: string[];
  sources?: Array<{ label: string; url: string }>;
}

const lifecycleOrder = KEN_LIFECYCLE_STAGES.map((stage) => stage.label.replace(/^\d+\s*·\s*/, "")).join(" -> ");
const laneRules = Object.values(LANE_OPERATING_POLICIES)
  .map((lane) => `${lane.label}: ${lane.bondCredits} bond credit${lane.bondCredits === 1 ? "" : "s"}; ${lane.checkpointCadence}`)
  .join(". ");

export const GLOSSARY_ENTRIES: GlossaryEntry[] = [
  {
    id: "ken",
    label: "Ken",
    plainDefinition: "A public work order for a difficult problem that may need sustained AI-assisted effort.",
    operationalDefinition: "A bounded record containing a problem statement, evidence, public-benefit case, deliverables, requested lane, risks, checkpoints, discussion, ranking signals, and an auditable outcome.",
    implementation: ["src/lib/types.ts", "src/lib/db.ts", "src/app/kens/[slug]/page.tsx"],
    governingRules: ["A Ken must remain inspectable from intake through delivery.", "Money cannot purchase rank or checkpoint approval."],
    status: "sandbox",
    relatedTerms: ["lifecycle", "checkpoint", "lane", "public-benefit"],
    route: "/kens",
    keywords: ["proposal", "work order", "task", "long horizon", "ai work"],
  },
  {
    id: "public-pulse",
    label: "Public pulse",
    plainDefinition: "A quick signal of support or concern.",
    operationalDefinition: "An account-attributed directional reaction used as a breadth signal. Pulse is distinct from scarce allocation voice and does not itself assign a lane.",
    implementation: ["src/app/actions.ts", "src/lib/db.ts", "src/components/task-card.tsx"],
    governingRules: ["One current pulse position per account and Ken.", "Pulse never converts sponsor money into rank."],
    status: "operational",
    relatedTerms: ["allocation-credit", "quadratic-cost", "public-board"],
    route: "/kens",
    keywords: ["upvote", "downvote", "support", "concern", "breadth"],
  },
  {
    id: "allocation-credit",
    label: "Allocation credit / voice",
    plainDefinition: "Scarce, non-purchasable influence used to express how strongly a contributor prioritizes a Ken.",
    operationalDefinition: `A verified account begins with ${INITIAL_ALLOCATION_CREDITS} credits and can receive a ${MONTHLY_REPLENISHMENT_CREDITS}-credit monthly refresh under current policy. Concentrating multiple votes on one Ken incurs quadratic cost.`,
    implementation: ["src/lib/allocation.ts", "src/lib/allocation-policy.ts", "src/app/actions.ts"],
    governingRules: [`Initial balance = ${INITIAL_ALLOCATION_CREDITS}.`, `Monthly refresh = ${MONTHLY_REPLENISHMENT_CREDITS}.`, "Credits are earned or replenished, not sold."],
    status: "operational",
    relatedTerms: ["public-pulse", "quadratic-cost", "quality-bond"],
    route: "/governance#voice",
    keywords: ["voice", "credit", "vote", "token", "non-purchasable"],
  },
  {
    id: "quadratic-cost",
    label: "Quadratic cost",
    plainDefinition: "Each additional unit of concentrated voice costs progressively more.",
    operationalDefinition: "The cost of assigning n voice units to one Ken is n² credits. One unit costs 1, two cost 4, and three cost 9.",
    implementation: ["src/lib/allocation-policy.ts", "src/lib/allocation.ts", "tests/allocation.test.ts"],
    governingRules: ["cost(n) = n²", "Cost is calculated per account and Ken."],
    status: "operational",
    relatedTerms: ["allocation-credit", "public-pulse", "sybil-risk-band"],
    route: "/governance#voice",
    keywords: ["formula", "square", "quadratic voting", "concentration"],
  },
  {
    id: "quality-bond",
    label: "Quality bond",
    plainDefinition: "Credits temporarily committed with a proposal to discourage low-effort submissions.",
    operationalDefinition: "The requested lane determines a bounded bond. A useful, review-ready proposal can earn credit under policy; abuse and spam do not.",
    implementation: ["src/lib/allocation-policy.ts", "src/app/actions.ts", "src/app/submit/page.tsx"],
    governingRules: [laneRules, "A bond is allocation voice, not a cash payment."],
    status: "operational",
    relatedTerms: ["lane", "intake-review", "allocation-credit"],
    route: "/submit",
    keywords: ["stake", "submission", "spam", "bond"],
  },
  {
    id: "category",
    label: "Category",
    plainDefinition: "A public-interest domain in which Kens are compared.",
    operationalDefinition: "A durable taxonomy record with a normalized slug and deterministic visual identity. Lane positions are category-local rather than one global ranking.",
    implementation: ["src/lib/taxonomy.ts", "src/lib/db.ts", "src/components/category-symbol.tsx"],
    governingRules: ["Names and slugs must be unique after normalization.", "Every current and future category receives a deterministic visual."],
    status: "operational",
    relatedTerms: ["category-proposal", "lane", "public-board"],
    route: "/kens",
    keywords: ["domain", "taxonomy", "filter", "topic"],
  },
  {
    id: "category-proposal",
    label: "Category proposal",
    plainDefinition: "A request to add a new public-interest domain.",
    operationalDefinition: "A signed-in submission reviewed for duplicate names, coherent boundaries, examples, safety, and public benefit before becoming a persistent category.",
    implementation: ["src/components/category-proposal-form.tsx", "src/lib/db.ts", "src/app/admin/page.tsx"],
    governingRules: ["Proposals do not publish categories automatically.", "Every decision must retain a reason-coded audit event."],
    status: "operational",
    relatedTerms: ["category", "intake-review", "audit-log"],
    route: "/submit#category-proposal",
    keywords: ["new category", "taxonomy proposal", "review"],
  },
  {
    id: "lane",
    label: "Lane / tier",
    plainDefinition: "A run-duration and review-cadence class.",
    operationalDefinition: "Public copy uses lane. The internal AllocationTier/RequestedTier types preserve compatibility. Days, Weeks, and Months are ranked category-locally; Queued and Blocked are non-running states.",
    implementation: ["src/lib/allocation.ts", "src/lib/taxonomy.ts", "src/components/lane-chip-link.tsx"],
    governingRules: [laneRules],
    status: "operational",
    relatedTerms: ["days-lane", "weeks-lane", "months-lane", "queued-lane", "blocked-lane"],
    route: "/kens",
    keywords: ["tier", "duration", "run", "rank"],
  },
  {
    id: "days-lane",
    label: "Days lane",
    plainDefinition: "Focused work with a short runtime and a clear acceptance check.",
    operationalDefinition: LANE_OPERATING_POLICIES.days.bestFor,
    implementation: ["src/lib/allocation-policy.ts", "src/lib/allocation.ts"],
    governingRules: [`Bond = ${LANE_OPERATING_POLICIES.days.bondCredits}.`, `Checkpoints: ${LANE_OPERATING_POLICIES.days.checkpointCadence}.`],
    status: "sandbox",
    relatedTerms: ["lane", "checkpoint", "run-budget"],
    route: "/kens?tier=days",
    keywords: ["short", "focused", "days", "tier"],
  },
  {
    id: "weeks-lane",
    label: "Weeks lane",
    plainDefinition: "Multi-step work with visible weekly progress.",
    operationalDefinition: LANE_OPERATING_POLICIES.weeks.bestFor,
    implementation: ["src/lib/allocation-policy.ts", "src/lib/allocation.ts"],
    governingRules: [`Bond = ${LANE_OPERATING_POLICIES.weeks.bondCredits}.`, `Checkpoints: ${LANE_OPERATING_POLICIES.weeks.checkpointCadence}.`],
    status: "sandbox",
    relatedTerms: ["lane", "checkpoint", "run-budget"],
    route: "/kens?tier=weeks",
    keywords: ["medium", "weeks", "multi-step", "tier"],
  },
  {
    id: "months-lane",
    label: "Months lane",
    plainDefinition: "Long-horizon work with recurring milestone and release reviews.",
    operationalDefinition: LANE_OPERATING_POLICIES.months.bestFor,
    implementation: ["src/lib/allocation-policy.ts", "src/lib/allocation.ts"],
    governingRules: [`Bond = ${LANE_OPERATING_POLICIES.months.bondCredits}.`, `Checkpoints: ${LANE_OPERATING_POLICIES.months.checkpointCadence}.`],
    status: "sandbox",
    relatedTerms: ["lane", "checkpoint", "run-budget"],
    route: "/kens?tier=months",
    keywords: ["long horizon", "months", "milestone", "tier"],
  },
  {
    id: "queued-lane",
    label: "Queued",
    plainDefinition: "Eligible work still waiting for signal, review, capacity, or scheduling.",
    operationalDefinition: "A non-running state that preserves rank and the public record while prerequisites or capacity remain unresolved.",
    implementation: ["src/lib/allocation.ts", "src/app/kens/page.tsx"],
    governingRules: ["Queued does not mean rejected.", "Funding cannot move a Ken ahead by purchasing rank."],
    status: "operational",
    relatedTerms: ["lane", "funding-capacity-state", "board-approval"],
    route: "/kens?tier=queued",
    keywords: ["queue", "waiting", "pending", "capacity"],
  },
  {
    id: "blocked-lane",
    label: "Blocked",
    plainDefinition: "Work held from execution with a visible reason.",
    operationalDefinition: "A non-running state for safety, validity, evidence, scope, or checkpoint failures. The record remains visible unless privacy or law requires restricted handling.",
    implementation: ["src/lib/allocation.ts", "src/lib/db.ts", "src/app/kens/[slug]/page.tsx"],
    governingRules: ["Blocked records require a reason.", "Public evidence is not silently deleted."],
    status: "operational",
    relatedTerms: ["safety-validity-review", "early-completion", "audit-log"],
    route: "/kens?tier=blocked",
    keywords: ["blocked", "hold", "safety", "failure reason"],
  },
  {
    id: "lifecycle",
    label: "Ken lifecycle",
    plainDefinition: "The public path from a draft idea to delivery and audit.",
    operationalDefinition: lifecycleOrder,
    implementation: ["src/lib/allocation-policy.ts", "src/components/ken-timing-strip.tsx"],
    governingRules: ["Stage order comes from KEN_LIFECYCLE_STAGES.", "Each transition must retain a visible reason or gate."],
    status: "sandbox",
    relatedTerms: ["intake-review", "board-approval", "checkpoint", "post-run-audit"],
    route: "/governance#lifecycle",
    keywords: ["stages", "workflow", "process", "timeline"],
  },
  {
    id: "intake-review",
    label: "Intake review",
    plainDefinition: "The readiness check before a submitted Ken enters public voting.",
    operationalDefinition: "Schema, duplication, public benefit, evaluation readiness, scope, and risk checks produce a review status and reasoned decision.",
    implementation: ["src/app/actions.ts", "src/lib/db.ts", "src/app/admin/page.tsx"],
    governingRules: ["Publication requires an explicit approval.", "Revision and rejection decisions retain reasons."],
    status: "proposed",
    relatedTerms: ["category-proposal", "board-approval", "safety-validity-review"],
    route: "/faq#submitted-ken-review",
    keywords: ["submission review", "readiness", "queue", "approval"],
  },
  {
    id: "board-approval",
    label: "Board approval",
    plainDefinition: "The recorded decision that an eligible Ken may be scheduled.",
    operationalDefinition: "A reasoned transition after readiness, safety, ranking, capacity, and checkpoint requirements are visible. It is not a sponsor purchase.",
    implementation: ["src/lib/allocation.ts", "src/lib/db.ts"],
    governingRules: ["Eligibility precedes lane allocation.", "Approval and scheduling remain distinguishable."],
    status: "sandbox",
    relatedTerms: ["public-board", "lane", "release-gate"],
    route: "/governance#lifecycle",
    keywords: ["approve", "schedule", "launch", "board"],
  },
  {
    id: "checkpoint",
    label: "Checkpoint",
    plainDefinition: "A public progress record during a run.",
    operationalDefinition: "A timestamped update with status, artifacts, evidence, risk changes, budget use, and a requested gate decision.",
    implementation: ["src/lib/types.ts", "src/lib/db.ts", "src/app/kens/[slug]/page.tsx"],
    governingRules: ["Checkpoints are append-only evidence.", "Cadence depends on lane."],
    status: "sandbox",
    relatedTerms: ["checkpoint-gate", "evidence-provenance", "run-budget"],
    route: "/kens",
    keywords: ["milestone", "progress", "update", "review"],
  },
  {
    id: "checkpoint-gate",
    label: "Checkpoint gate",
    plainDefinition: "A continue, redirect, pause, partial-release, or block decision.",
    operationalDefinition: "A reason-coded review of acceptance criteria, provenance, safety, scope, and remaining budget at a checkpoint.",
    implementation: ["src/lib/types.ts", "src/lib/db.ts", "src/app/kens/[slug]/page.tsx"],
    governingRules: ["No color-only decision meaning.", "The reason and reviewer context remain auditable."],
    status: "sandbox",
    relatedTerms: ["checkpoint", "release-gate", "partial-delivery"],
    route: "/governance#checkpoints",
    keywords: ["continue", "pause", "redirect", "block", "decision"],
  },
  {
    id: "run-budget",
    label: "Run budget / runtime cap",
    plainDefinition: "The maximum approved compute or elapsed runtime for a Ken.",
    operationalDefinition: "A bounded operating limit attached to the run plan. Reaching it requires a reasoned stop, partial delivery, or separately approved extension.",
    implementation: ["src/lib/types.ts", "src/lib/economics.ts", "src/app/kens/[slug]/page.tsx"],
    governingRules: ["No unlimited run promise.", "Extensions cannot bypass rank or checkpoint review."],
    status: "sandbox",
    relatedTerms: ["lane", "checkpoint-gate", "funding-capacity-state"],
    route: "/economics",
    keywords: ["budget", "runtime", "cap", "compute", "hours"],
  },
  {
    id: "rollback-plan",
    label: "Rollback plan",
    plainDefinition: "A documented way to reverse a harmful or failed release.",
    operationalDefinition: "Named restoration steps, preserved evidence, responsible roles, and verification criteria attached before a risky launch.",
    implementation: ["docs/synology-nas-deploy.md", "src/lib/allocation-policy.ts"],
    governingRules: ["Use a recorded revert or verified backup.", "Never erase public history with an unrecorded force reset."],
    status: "operational",
    relatedTerms: ["release-gate", "audit-log", "evidence-provenance"],
    route: "/governance",
    keywords: ["restore", "revert", "backup", "recovery"],
  },
  {
    id: "release-gate",
    label: "Release gate",
    plainDefinition: "The final check before an output is represented as delivered.",
    operationalDefinition: "A review of named deliverables, acceptance criteria, provenance, safety, corrections, and limitations resulting in release, partial release, redirect, or rejection.",
    implementation: ["src/lib/allocation-policy.ts", "src/lib/db.ts"],
    governingRules: ["A status change requires a reason.", "Sponsor support cannot override the gate."],
    status: "sandbox",
    relatedTerms: ["checkpoint-gate", "partial-delivery", "post-run-audit"],
    route: "/governance#checkpoints",
    keywords: ["release", "ship", "acceptance", "approval"],
  },
  {
    id: "partial-delivery",
    label: "Partial delivery",
    plainDefinition: "Useful, verified output released when the full promise cannot be completed.",
    operationalDefinition: "A release state that names completed and incomplete deliverables, limitations, remaining risks, and the reason work stopped.",
    implementation: ["src/lib/types.ts", "src/app/kens/[slug]/page.tsx"],
    governingRules: ["Partial does not mean complete.", "The unfulfilled scope remains visible."],
    status: "proposed",
    relatedTerms: ["release-gate", "early-completion", "post-run-audit"],
    route: "/faq#quality-contract",
    keywords: ["partial", "incomplete", "deliverable", "limitations"],
  },
  {
    id: "early-completion",
    label: "Early completion / termination",
    plainDefinition: "A run ending before its maximum runtime, either successfully or for a documented stop reason.",
    operationalDefinition: "A reason-coded terminal or paused decision for successful early completion, safety, acceptance failure, provenance failure, cap exhaustion, provider failure, duplication, scope invalidation, or operational emergency.",
    implementation: ["src/lib/types.ts", "src/lib/db.ts"],
    governingRules: ["No run silently disappears.", "Successful early completion is distinct from failure."],
    status: "proposed",
    relatedTerms: ["run-budget", "partial-delivery", "audit-log"],
    route: "/faq#stop-conditions",
    keywords: ["termination", "stop", "early", "pause", "failure"],
  },
  {
    id: "post-run-audit",
    label: "Post-run audit",
    plainDefinition: "The final public record of what worked, failed, and should change.",
    operationalDefinition: "A review of delivered artifacts, acceptance evidence, corrections, spend, provider behavior, reviewer decisions, and contributor-credit rationale.",
    implementation: ["src/lib/allocation-policy.ts", "src/lib/db.ts"],
    governingRules: ["Audit follows public delivery or a terminal stop.", "Credit awards point to visible useful work."],
    status: "sandbox",
    relatedTerms: ["audit-log", "attestation", "evidence-provenance"],
    route: "/governance#lifecycle",
    keywords: ["audit", "retrospective", "outcome", "correction"],
  },
  {
    id: "attestation",
    label: "Attestation",
    plainDefinition: "Evidence supporting a contributor’s identity, expertise, or track record.",
    operationalDefinition: "A bounded claim reviewed by an authorized role and used to inform participation capacity; it is not a guarantee that every future contribution is correct.",
    implementation: ["src/lib/attestation.ts", "src/app/verification/page.tsx", "src/lib/db.ts"],
    governingRules: ["Evidence is reviewed, not purchased.", "Public display excludes private verification material."],
    status: "operational",
    relatedTerms: ["verification", "sybil-risk-band", "allocation-credit"],
    route: "/verification",
    keywords: ["expertise", "identity", "evidence", "credential"],
  },
  {
    id: "verification",
    label: "Verification",
    plainDefinition: "The account and evidence checks that support accountable participation.",
    operationalDefinition: "Email verification is required for core account participation; optional reviewed attestations can support a higher contribution capacity without conferring correctness or authority.",
    implementation: ["src/lib/session.ts", "src/lib/db.ts", "src/app/verification/page.tsx"],
    governingRules: ["Verification status is explicit.", "Sensitive evidence is not exposed publicly."],
    status: "operational",
    relatedTerms: ["attestation", "sybil-risk-band", "allocation-credit"],
    route: "/verification",
    keywords: ["email", "account", "verified", "identity"],
  },
  {
    id: "sybil-risk-band",
    label: "Sybil-risk band",
    plainDefinition: "A bounded account-risk classification used to limit coordinated fake-account influence.",
    operationalDefinition: "A deterministic policy outcome that can preserve full participation, cap voice temporarily, or make an account read-only pending review.",
    implementation: ["src/lib/attestation.ts", "src/lib/security.ts", "tests/attestation.test.ts"],
    governingRules: ["Low risk retains ordinary capacity.", "Higher risk triggers bounded review, not secret ranking changes."],
    status: "operational",
    relatedTerms: ["verification", "attestation", "public-pulse"],
    route: "/verification",
    keywords: ["sybil", "abuse", "risk", "account", "brigading"],
  },
  {
    id: "public-board",
    label: "Public board / allocation chamber",
    plainDefinition: "The shared surface where Kens are proposed, discussed, ranked, and monitored.",
    operationalDefinition: "The Feed, Ken details, governance records, and public checkpoints together form the board. It is a process and record, not a secret committee.",
    implementation: ["src/app/kens/page.tsx", "src/app/kens/[slug]/page.tsx", "src/app/governance/page.tsx"],
    governingRules: ["Ranking evidence is public.", "Review roles do not receive private ranking power."],
    status: "sandbox",
    relatedTerms: ["ken", "public-pulse", "board-approval"],
    route: "/kens",
    keywords: ["board", "chamber", "feed", "governance", "public"],
  },
  {
    id: "safety-validity-review",
    label: "Safety / validity review",
    plainDefinition: "A bounded review of whether a Ken may be run and whether its evidence can support its claims.",
    operationalDefinition: "A reason-coded human review informed by deterministic schema, boundary, and readiness warnings. Subjective judgment is labeled as such.",
    implementation: ["src/lib/security.ts", "src/lib/db.ts", "src/app/admin/page.tsx"],
    governingRules: ["Automated warnings are advisory unless a documented hard rule applies.", "High-impact holds require audit evidence."],
    status: "sandbox",
    relatedTerms: ["intake-review", "checkpoint-gate", "moderation-role"],
    route: "/governance",
    keywords: ["safety", "validity", "review", "risk", "human"],
  },
  {
    id: "sponsor-restriction",
    label: "Sponsor restriction",
    plainDefinition: "A disclosed condition limiting what donated support may fund.",
    operationalDefinition: "A sponsor record may target a public pool, category, or Ken. Restrictions affect usable funding, never rank, voting, safety, or release authority.",
    implementation: ["src/lib/economics.ts", "src/lib/db.ts", "src/app/economics/page.tsx"],
    governingRules: ["Every restriction is visible.", "Restricted funds cannot be silently reclassified."],
    status: "sandbox",
    relatedTerms: ["support-state", "treasury", "coverage"],
    route: "/economics",
    keywords: ["sponsor", "restricted funds", "backing", "donation"],
  },
  {
    id: "support-state",
    label: "Committed / projected / simulated support",
    plainDefinition: "Labels that separate actual commitments from forecasts and demonstrations.",
    operationalDefinition: "Committed means recorded as available under an actual agreement; projected is a forecast; simulated is clearly marked sandbox data. The public prototype currently uses simulated support.",
    implementation: ["src/lib/economics.ts", "src/lib/types.ts", "src/app/economics/page.tsx"],
    governingRules: ["Simulation is never presented as settled money.", "Forecasts do not count as available cash."],
    status: "sandbox",
    relatedTerms: ["treasury", "reserve", "coverage"],
    route: "/economics",
    keywords: ["committed", "projected", "simulated", "funding state"],
  },
  {
    id: "treasury",
    label: "Treasury",
    plainDefinition: "The ledger of support available for compute, review, and operations.",
    operationalDefinition: "A structured accounting surface separating funding states, restrictions, simulated spend, reserves, and operating coverage.",
    implementation: ["src/lib/economics.ts", "src/lib/db.ts", "src/app/economics/page.tsx"],
    governingRules: ["Treasury support cannot buy rank.", "Public figures identify sandbox state."],
    status: "sandbox",
    relatedTerms: ["reserve", "coverage", "sponsor-restriction"],
    route: "/economics",
    keywords: ["funding", "money", "pool", "ledger"],
  },
  {
    id: "reserve",
    label: "Reserve",
    plainDefinition: "Support held back for safe continuity, maintenance, or unexpected costs.",
    operationalDefinition: "A treasury allocation excluded from ordinary new-run capacity until a documented release condition is met.",
    implementation: ["src/lib/economics.ts", "src/app/economics/page.tsx"],
    governingRules: ["Reserve use requires a visible purpose.", "Reserved support is not available-run coverage."],
    status: "sandbox",
    relatedTerms: ["treasury", "coverage", "funding-capacity-state"],
    route: "/economics",
    keywords: ["reserve", "buffer", "maintenance", "continuity"],
  },
  {
    id: "coverage",
    label: "Coverage",
    plainDefinition: "How much planned work current usable support can sustain.",
    operationalDefinition: "A derived comparison between unrestricted/relevantly restricted support and approved operating demand. It is an estimate, not a guarantee.",
    implementation: ["src/lib/economics.ts", "src/app/economics/page.tsx", "tests/economics.test.ts"],
    governingRules: ["Coverage excludes unavailable or mismatched restricted funds.", "Projected coverage is labeled."],
    status: "sandbox",
    relatedTerms: ["treasury", "reserve", "run-budget"],
    route: "/economics",
    keywords: ["runway", "funding", "capacity", "estimate"],
  },
  {
    id: "funding-capacity-state",
    label: "Funding / capacity state",
    plainDefinition: "The operating mode used when available support changes.",
    operationalDefinition: "A transparent state such as normal, constrained, new-launches-paused, or critical-maintenance-only that changes scheduling while preserving the public board and records.",
    implementation: ["src/lib/run-governance.ts", "src/lib/economics.ts", "src/lib/db.ts", "src/app/economics/page.tsx", "src/components/site-shell.tsx"],
    governingRules: ["Low funding pauses execution, not public history.", "Existing runs continue only to a safe checkpoint when policy permits."],
    status: "operational",
    relatedTerms: ["coverage", "queued-lane", "run-budget"],
    route: "/faq#funding-scarcity",
    keywords: ["funding shortage", "capacity", "paused", "maintenance"],
  },
  {
    id: "public-benefit",
    label: "Public benefit",
    plainDefinition: "Value that is inspectable and meaningfully available beyond a private requester.",
    operationalDefinition: "A stated beneficiary, reusable or public artifact, and evidence that the work addresses a shared need. Review remains human judgment and is labeled subjective.",
    implementation: ["src/lib/types.ts", "src/app/submit/page.tsx", "src/lib/allocation-policy.ts"],
    governingRules: ["A private chat request is not sufficient.", "Claims require named beneficiaries and deliverables."],
    status: "operational",
    relatedTerms: ["ken", "intake-review", "safety-validity-review"],
    route: "/submit",
    keywords: ["benefit", "public good", "shared", "value"],
  },
  {
    id: "sandbox",
    label: "Sandbox / demo state",
    plainDefinition: "A production-shaped demonstration whose money, execution, users, or outcomes are simulated.",
    operationalDefinition: "A visible disclosure applied to seeded sponsor totals, model execution, run progress, pilot users, and sample outcomes until an actual provider or settlement is configured and verified.",
    implementation: ["src/lib/seed.ts", "src/lib/seed-plus.ts", "src/app/page.tsx"],
    governingRules: ["Simulated values must be labeled near the claim.", "Sandbox results are not evidence of real provider delivery."],
    status: "operational",
    relatedTerms: ["support-state", "trust-surface", "evidence-provenance"],
    route: "/faq#sandbox-status",
    keywords: ["demo", "prototype", "simulation", "not real"],
  },
  {
    id: "moderation-role",
    label: "Moderation / review role",
    plainDefinition: "A narrowly scoped responsibility for triage, revision requests, risk holds, and reasoned review.",
    operationalDefinition: "Role-bound actions are authorization checked and audited. Moderation labor is separate from ranking power; recusal, appeal, and second review constrain high-impact decisions.",
    implementation: ["src/lib/session.ts", "src/lib/db.ts", "src/app/admin/page.tsx"],
    governingRules: ["No silent deletion.", "No voice award merely for moderation volume.", "Conflicts require recusal."],
    status: "operational",
    relatedTerms: ["safety-validity-review", "audit-log", "public-board"],
    route: "/faq#moderation-boundaries",
    keywords: ["moderator", "reviewer", "appeal", "recusal", "role"],
  },
  {
    id: "audit-log",
    label: "Audit log",
    plainDefinition: "An append-only record of important decisions and mutations.",
    operationalDefinition: "A timestamped actor, action, target, and bounded details record used for accountable admin, review, funding, and lifecycle operations.",
    implementation: ["src/lib/db.ts", "src/app/admin/page.tsx"],
    governingRules: ["Public outcomes retain public reasons.", "Private bodies and secrets stay access controlled."],
    status: "operational",
    relatedTerms: ["evidence-provenance", "moderation-role", "post-run-audit"],
    route: "/faq#trust-status",
    keywords: ["audit", "log", "history", "decision", "immutable"],
  },
  {
    id: "evidence-provenance",
    label: "Evidence provenance",
    plainDefinition: "The trace showing where a claim, source, artifact, or result came from.",
    operationalDefinition: "Source links, timestamps, digests, actor/reviewer context, and state labels sufficient to distinguish observed evidence from inference, simulation, or external dependency.",
    implementation: ["src/lib/types.ts", "src/lib/db.ts", "src/app/kens/[slug]/page.tsx"],
    governingRules: ["Claims identify their evidence state.", "Sensitive or private source material is not made public by default."],
    status: "sandbox",
    relatedTerms: ["checkpoint", "post-run-audit", "trust-surface"],
    route: "/governance",
    keywords: ["source", "origin", "evidence", "digest", "trace"],
  },
  {
    id: "trust-surface",
    label: "Implementation-status truth surface",
    plainDefinition: "A public matrix stating what works now, what is simulated, and what remains proposed or externally dependent.",
    operationalDefinition: "A maintained disclosure linking product claims to current implementation mode and material limitations without exposing private records or security details.",
    implementation: ["src/lib/product-truth.ts", "src/app/faq/page.tsx"],
    governingRules: ["No future capability is described as operational.", "Every sandbox claim remains visibly labeled."],
    status: "operational",
    relatedTerms: ["sandbox", "evidence-provenance", "support-state"],
    route: "/faq#trust-status",
    keywords: ["trust", "status", "implemented", "proposed", "truth"],
  },
];

export function filterGlossaryEntries(
  entries: GlossaryEntry[],
  query: string,
  status: GlossaryStatus | "all",
) {
  const normalized = normalizeSearchText(query);
  return entries.filter((entry) => {
    if (status !== "all" && entry.status !== status) return false;
    if (!normalized) return true;
    return normalizeSearchText([
      entry.label,
      entry.plainDefinition,
      entry.operationalDefinition,
      ...entry.governingRules,
      ...entry.relatedTerms,
      ...entry.keywords,
    ].join(" ")).includes(normalized);
  });
}

export function getGlossaryEntry(id: string) {
  return GLOSSARY_ENTRIES.find((entry) => entry.id === id) ?? null;
}
