import type { CategoryRecord, CheckpointRecord, ComputeRunRecord, GovernanceEventRecord, ProfileRecord, TaskRecord, VoteRecord } from "@/lib/types";

export const seedProfiles: ProfileRecord[] = [
  { id: "maya-chen", name: "Maya Chen", role: "Open-source maintainer", bio: "Keeps critical software releases stable and reproducible.", specialty: "Release reliability", attestation: "Signed maintainer history and review", voiceCredits: 64, credibility: 0.95, avatarHue: 18 },
  { id: "noor-haddad", name: "Noor Haddad", role: "Biomedical researcher", bio: "Builds evidence maps for small labs and patient communities.", specialty: "Rare-disease synthesis", attestation: "ORCID-linked publication history", voiceCredits: 82, credibility: 0.97, avatarHue: 152 },
  { id: "rafael-ortiz", name: "Rafael Ortiz", role: "Public-interest technologist", bio: "Turns civic complexity into tools people can actually use.", specialty: "Civic services", attestation: "Verified nonprofit portfolio", voiceCredits: 54, credibility: 0.92, avatarHue: 206 },
  { id: "elena-petrov", name: "Elena Petrov", role: "Security engineer", bio: "Works on defensive software tooling and incident response.", specialty: "Defensive operations", attestation: "Signed security maintainer attestations", voiceCredits: 38, credibility: 0.93, avatarHue: 340 },
  { id: "aiko-tanaka", name: "Aiko Tanaka", role: "Creative technologist", bio: "Builds interfaces and media tools that make complexity feel usable.", specialty: "Experience design", attestation: "Portfolio review and long-term references", voiceCredits: 46, credibility: 0.9, avatarHue: 276 },
  { id: "jordan-miles", name: "Jordan Miles", role: "Policy analyst", bio: "Translates public rules into clearer steps, deadlines, and choices.", specialty: "Benefits and procurement", attestation: "Policy clinic fellowship", voiceCredits: 31, credibility: 0.88, avatarHue: 44 },
  { id: "priya-singh", name: "Priya Singh", role: "Operations lead", bio: "Connects research teams, clinics, and service organizations to delivery workflows.", specialty: "Program operations", attestation: "Independent consortium reference checks", voiceCredits: 51, credibility: 0.91, avatarHue: 118 },
];

export const seedCategories: CategoryRecord[] = [
  { id: "everyday-services", slug: "everyday-services", name: "Everyday Services", description: "Helpful Kens for household decisions, paperwork, repairs, and local opportunities.", thesis: "Frontier compute should help people with costly, recurring decisions still buried in scattered documents." },
  { id: "public-interest", slug: "public-interest", name: "Public Interest", description: "Civic, environmental, and nonprofit workflows with broad public upside.", thesis: "Continuous AI becomes defensible when it keeps critical local information fresh and source-grounded." },
  { id: "open-tools", slug: "open-tools", name: "Open Tools", description: "Shared software and reliability infrastructure that others can reuse.", thesis: "Some of the highest-value Kens make later Kens cheaper, safer, and easier to audit." },
  { id: "science-health", slug: "science-health", name: "Science and Health", description: "Long-horizon evidence maps and carefully supervised research support.", thesis: "Small labs and clinics rarely need one more demo; they need continuity, provenance, and revision trails." },
  { id: "creative-works", slug: "creative-works", name: "Creative and Cultural", description: "Creative, functional, and preservation-oriented Kens for artists, educators, and communities.", thesis: "Cultural and creative work counts when it produces open tools, reusable archives, and practical public value." },
];

export const seedTasks: TaskRecord[] = [
  { id: "home-energy-upgrade-companion", slug: "home-energy-upgrade-companion", categoryId: "everyday-services", proposerId: "rafael-ortiz", title: "Home Energy Upgrade Companion", summary: "Turn utility bills, local rebates, and weather data into a plain-language plan for lowering household energy costs.", problem: "People still have to compare disconnected rebate rules, contractor guidance, and utility usage on their own.", whyNow: "Energy costs remain volatile and households need a source-grounded assistant that stays current.", publicBenefit: "Produces reusable home-upgrade plans, clearly cited savings assumptions, and checklists nonprofits can adapt.", deliverables: ["Household plan template", "Rebate parser", "Source-linked savings assumptions"], evaluationCriteria: ["Every recommendation cites a rule or bill line", "Outputs remain editable", "Savings estimates stay within published ranges"], riskFlags: ["No financing advice without disclosures", "Flag stale local data"], evidence: ["Utility rate schedules", "Municipal rebate pages", "Weather-normalized usage records"], requestedTier: "weeks", stage: "running", safetyStatus: "approved", budgetUsd: 18000, runtimeHours: 220, backend: "Hybrid API routing with municipal rules index", createdAt: "2026-03-01T09:00:00.000Z" },
  { id: "repair-manual-finder", slug: "repair-manual-finder", categoryId: "everyday-services", proposerId: "maya-chen", title: "Repair Manual Finder for Older Appliances", summary: "Locate hard-to-find manuals, parts diagrams, and known fixes for older appliances before people replace them.", problem: "Useful repair information is scattered across forums, scans, and vendor archives.", whyNow: "Households are trying to stretch equipment life, but reliable repair guidance remains fragmented.", publicBenefit: "Helps people fix existing equipment and produces openly shareable repair packets for community workshops.", deliverables: ["Repair packet generator", "Parts cross-reference sheet", "Manual provenance log"], evaluationCriteria: ["Packets include model verification steps", "Every repair note links to a source", "Users can contest wrong matches"], riskFlags: ["Do not fabricate safety procedures", "Flag incomplete manuals"], evidence: ["Service manual archives", "Manufacturer parts catalogs", "Repair forum confirmations"], requestedTier: "days", stage: "shipped", safetyStatus: "approved", budgetUsd: 5000, runtimeHours: 72, backend: "Search index plus lightweight OCR workers", createdAt: "2026-02-25T11:20:00.000Z" },
  { id: "benefit-appeal-packet-helper", slug: "benefit-appeal-packet-helper", categoryId: "public-interest", proposerId: "jordan-miles", title: "Benefit Appeal Packet Helper", summary: "Turn denial letters and program rules into editable appeal packets for caseworkers and legal-aid teams.", problem: "People lose benefits because the appeal path is document-heavy, deadline-sensitive, and hard to parse under stress.", whyNow: "This work is repetitive, high stakes, and frequently delayed by staffing shortages.", publicBenefit: "Helps advocates move faster without pretending to replace them, and keeps every suggested argument tied to a public source.", deliverables: ["Editable packet draft", "Rule citation map", "Deadline checklist"], evaluationCriteria: ["Every recommendation cites the relevant rule", "Advocates can revise outputs quickly", "No output implies legal advice"], riskFlags: ["Jurisdiction differences matter", "Flag ambiguity instead of bluffing"], evidence: ["Program manuals", "Appeal forms", "Legal-aid workflow notes"], requestedTier: "weeks", stage: "scheduled", safetyStatus: "approved", budgetUsd: 15000, runtimeHours: 168, backend: "Local rules index with supervised drafting", createdAt: "2026-03-03T10:40:00.000Z" },
  { id: "small-town-procurement-checker", slug: "small-town-procurement-checker", categoryId: "public-interest", proposerId: "jordan-miles", title: "Small-town Procurement Checker", summary: "Flag contradictions, inaccessible language, and missing requirements in municipal purchasing documents.", problem: "Smaller jurisdictions often reuse brittle templates and do not have time to audit every draft manually.", whyNow: "Public technology contracts keep getting more complex while local review teams stay small.", publicBenefit: "Improves public procurement quality and makes bidding requirements easier for smaller vendors to understand.", deliverables: ["Specification linting pass", "Plain-language rewrite suggestions", "Issue log with source anchors"], evaluationCriteria: ["Flags map to explicit checks", "Jurisdictions can rerun locally", "False positives remain manageable"], riskFlags: ["Not legal advice", "Must show why a flag was raised"], evidence: ["Municipal RFP archives", "Accessibility guidance", "Procurement templates"], requestedTier: "days", stage: "voting", safetyStatus: "approved", budgetUsd: 5400, runtimeHours: 60, backend: "Structured document parser and rules runner", createdAt: "2026-03-09T14:10:00.000Z" },
  { id: "local-air-quality-briefing", slug: "local-air-quality-briefing", categoryId: "public-interest", proposerId: "rafael-ortiz", title: "Local Air Quality Briefing", summary: "Combine sensor alerts, school guidance, and neighborhood-specific risk notes into a daily public briefing.", problem: "Air-quality information is distributed across agency dashboards that are hard to compare when people need a simple answer fast.", whyNow: "Wildfire smoke and seasonal pollution spikes keep returning, but most communities still do not have an accessible local digest.", publicBenefit: "Supports families, schools, clinics, and local newsrooms with source-linked briefings they can use immediately.", deliverables: ["Regional morning briefing", "Neighborhood source map", "Plain-language protective actions"], evaluationCriteria: ["Every warning links to a live source", "Briefings update quickly enough to matter", "Language stays clear for non-specialists"], riskFlags: ["Do not invent health advice", "Escalate when sensor coverage is thin or conflicting"], evidence: ["EPA and local district feeds", "School closure notices", "Clinic advisory pages"], requestedTier: "months", stage: "running", safetyStatus: "approved", budgetUsd: 26000, runtimeHours: 720, backend: "Source monitoring mesh with alert deduplication", createdAt: "2026-02-27T07:30:00.000Z" },
  { id: "open-source-security-regression-watch", slug: "open-source-security-regression-watch", categoryId: "open-tools", proposerId: "elena-petrov", title: "Open-source Security Regression Watch", summary: "Replay critical dependency tests and publish rollback-ready security regressions before they spread downstream.", problem: "Security-sensitive regressions still reach users because downstream teams discover the same breakage independently and too late.", whyNow: "Long-running monitoring is finally practical, but trust depends on evidence bundles and explicit rollback paths.", publicBenefit: "Creates public incident packets, early warnings, and reproducible evidence many downstream teams can reuse.", deliverables: ["Replay harness", "Regression evidence bundle", "Rollback-ready diff summaries"], evaluationCriteria: ["Every alert links to a failing case", "False positives stay low", "Human reviewers can reproduce claims"], riskFlags: ["Never auto-merge fixes", "Protect embargoed details when necessary"], evidence: ["Dependency test suites", "Maintainer advisory threads", "Downstream incident reports"], requestedTier: "months", stage: "running", safetyStatus: "monitor", budgetUsd: 34000, runtimeHours: 720, backend: "Trusted CI runners plus isolated sandboxes", createdAt: "2026-02-26T12:00:00.000Z" },
  { id: "rare-disease-evidence-atlas", slug: "rare-disease-evidence-atlas", categoryId: "science-health", proposerId: "noor-haddad", title: "Rare-disease Evidence Atlas", summary: "Maintain a living map of hypotheses, interventions, contradictions, and open questions for understudied conditions.", problem: "Small research teams and patient groups rarely have the staffing needed to keep a rigorous synthesis map current.", whyNow: "Long-context systems can finally preserve competing explanations over time if the workflow keeps citations and checkpoints first.", publicBenefit: "Gives small labs and patient communities a continuously updated evidence layer instead of a one-off review.", deliverables: ["Source-grounded evidence map", "Contradiction log", "Priority questions for follow-up"], evaluationCriteria: ["Claims preserve uncertainty", "Every entry cites the source", "Experts can submit corrections efficiently"], riskFlags: ["Do not overstate clinical relevance", "Separate hypotheses from established evidence"], evidence: ["PubMed and preprint feeds", "Trial registries", "Foundation reports"], requestedTier: "months", stage: "running", safetyStatus: "approved", budgetUsd: 38000, runtimeHours: 720, backend: "Long-context retrieval and contradiction-preserving synthesis", createdAt: "2026-02-24T09:10:00.000Z" },
  { id: "clinic-follow-up-question-drafter", slug: "clinic-follow-up-question-drafter", categoryId: "science-health", proposerId: "priya-singh", title: "Clinic Follow-up Question Drafter", summary: "Generate concise, source-backed follow-up question sets for community clinics after complex specialist notes arrive.", problem: "Community clinics often receive dense specialist documents without enough staff time to turn them into clear follow-up actions.", whyNow: "A carefully supervised drafting workflow can save clinician time if it stays narrow, auditable, and easy to discard when uncertain.", publicBenefit: "Improves continuity of care in under-resourced settings without claiming diagnosis or replacing medical judgment.", deliverables: ["Question set draft", "Source-linked note summary", "Escalation flags for clinician review"], evaluationCriteria: ["Clinicians can audit each question", "Unsafe suggestions are rare", "Edits feed back into quality review"], riskFlags: ["No diagnostic claims", "Human sign-off required before use"], evidence: ["Specialist note templates", "Clinic follow-up protocols", "Quality-improvement reviews"], requestedTier: "days", stage: "shipped", safetyStatus: "monitor", budgetUsd: 6200, runtimeHours: 72, backend: "Retrieval-augmented drafting with clinician review queue", createdAt: "2026-02-23T15:30:00.000Z" },
  { id: "museum-oral-history-indexer", slug: "museum-oral-history-indexer", categoryId: "creative-works", proposerId: "aiko-tanaka", title: "Museum Oral History Indexer", summary: "Turn long audio interviews into searchable, quoted, and rights-aware story maps for small museums and community archives.", problem: "Small archives often record invaluable interviews but cannot afford the indexing and transcript cleanup needed to make them usable.", whyNow: "Transcription quality is improving, but the real bottleneck remains careful segmentation, rights notes, and searchable context.", publicBenefit: "Makes local history collections more discoverable for educators, families, and future researchers.", deliverables: ["Searchable transcript timeline", "Rights and consent notes", "Topic-linked exhibit snippets"], evaluationCriteria: ["Quotes stay aligned to timestamps", "Archives can correct metadata easily", "Public outputs respect rights restrictions"], riskFlags: ["Consent and access rules vary", "Must preserve speaker context"], evidence: ["Interview recordings", "Archive metadata", "Rights agreements"], requestedTier: "weeks", stage: "scheduled", safetyStatus: "approved", budgetUsd: 12000, runtimeHours: 144, backend: "Audio segmentation and metadata review pipeline", createdAt: "2026-03-05T13:45:00.000Z" },
  { id: "public-domain-performance-studio", slug: "public-domain-performance-studio", categoryId: "creative-works", proposerId: "aiko-tanaka", title: "Public-domain Performance Studio", summary: "Help schools and community theaters adapt public-domain material into usable rehearsal packets, staging notes, and rights-safe assets.", problem: "Small arts groups spend scarce time rediscovering what they are allowed to use and how to share materials cleanly.", whyNow: "Creative AI tooling is common, but rights-safe and rehearsal-ready workflows for low-budget groups are still rare.", publicBenefit: "Supports arts access, reduces legal confusion, and creates reusable production tools for educators and community performers.", deliverables: ["Rights-safe source finder", "Editable rehearsal packet", "Cue and scene breakdown"], evaluationCriteria: ["Every source is public-domain or clearly licensed", "Packets remain editable", "Groups can trace where every passage came from"], riskFlags: ["Avoid false rights claims", "Human review before public release"], evidence: ["Public-domain repositories", "Library scans", "Production planning templates"], requestedTier: "days", stage: "voting", safetyStatus: "approved", budgetUsd: 4800, runtimeHours: 54, backend: "Archive search plus structured production workflow", createdAt: "2026-03-10T12:25:00.000Z" },
  { id: "autonomous-phishing-lure-optimizer", slug: "autonomous-phishing-lure-optimizer", categoryId: "open-tools", proposerId: "maya-chen", title: "Autonomous Phishing Lure Optimizer", summary: "Continuously improve phishing messages, evasion tactics, and click-through performance against real targets.", problem: "The Ken directly improves offensive abuse capacity.", whyNow: "It should not launch.", publicBenefit: "None established.", deliverables: ["Not applicable"], evaluationCriteria: ["Not applicable"], riskFlags: ["Credential theft enablement", "Social-engineering optimization"], evidence: ["Safety review filing"], requestedTier: "months", stage: "blocked", safetyStatus: "blocked", budgetUsd: 0, runtimeHours: 0, backend: "Denied", createdAt: "2026-03-02T18:00:00.000Z" },
];

export const seedVotes: VoteRecord[] = [
  { id: "vote-1", taskId: "home-energy-upgrade-companion", profileId: "rafael-ortiz", voteCount: 6, rationale: "Practical, source-grounded, and immediately useful to households.", updatedAt: "2026-03-15T09:00:00.000Z" },
  { id: "vote-2", taskId: "home-energy-upgrade-companion", profileId: "jordan-miles", voteCount: 4, rationale: "A good fit for sustained work because the rules change constantly.", updatedAt: "2026-03-15T09:08:00.000Z" },
  { id: "vote-3", taskId: "local-air-quality-briefing", profileId: "rafael-ortiz", voteCount: 7, rationale: "Public-health value is clear and the sources are unusually legible.", updatedAt: "2026-03-15T09:12:00.000Z" },
  { id: "vote-4", taskId: "local-air-quality-briefing", profileId: "priya-singh", voteCount: 4, rationale: "Direct operational value for clinics and schools.", updatedAt: "2026-03-15T09:18:00.000Z" },
  { id: "vote-5", taskId: "benefit-appeal-packet-helper", profileId: "jordan-miles", voteCount: 5, rationale: "Advocates need this now, and the workflow stays bounded.", updatedAt: "2026-03-15T09:24:00.000Z" },
  { id: "vote-6", taskId: "benefit-appeal-packet-helper", profileId: "rafael-ortiz", voteCount: 3, rationale: "Useful to clinics and local nonprofits without replacing judgment.", updatedAt: "2026-03-15T09:26:00.000Z" },
  { id: "vote-7", taskId: "open-source-security-regression-watch", profileId: "elena-petrov", voteCount: 8, rationale: "Shared defensive infrastructure compounds across many teams.", updatedAt: "2026-03-15T09:31:00.000Z" },
  { id: "vote-8", taskId: "open-source-security-regression-watch", profileId: "maya-chen", voteCount: 5, rationale: "Replay plus rollback-ready output is exactly the right scope.", updatedAt: "2026-03-15T09:33:00.000Z" },
  { id: "vote-9", taskId: "rare-disease-evidence-atlas", profileId: "noor-haddad", voteCount: 7, rationale: "Continuity and contradiction handling are the real value here.", updatedAt: "2026-03-15T09:38:00.000Z" },
  { id: "vote-10", taskId: "rare-disease-evidence-atlas", profileId: "priya-singh", voteCount: 5, rationale: "A living evidence map is much more useful than another static review.", updatedAt: "2026-03-15T09:41:00.000Z" },
  { id: "vote-11", taskId: "museum-oral-history-indexer", profileId: "aiko-tanaka", voteCount: 4, rationale: "Small archives need a workflow, not one-off transcription.", updatedAt: "2026-03-15T09:44:00.000Z" },
  { id: "vote-12", taskId: "repair-manual-finder", profileId: "maya-chen", voteCount: 3, rationale: "Low glamour, high utility, and very reusable.", updatedAt: "2026-03-15T09:47:00.000Z" },
  { id: "vote-13", taskId: "clinic-follow-up-question-drafter", profileId: "priya-singh", voteCount: 2, rationale: "Worth running narrowly with strong clinician oversight.", updatedAt: "2026-03-15T09:50:00.000Z" },
  { id: "vote-14", taskId: "public-domain-performance-studio", profileId: "aiko-tanaka", voteCount: 3, rationale: "Creative work belongs here when outputs are rights-safe and reusable.", updatedAt: "2026-03-15T09:55:00.000Z" },
];

export const seedRuns: ComputeRunRecord[] = [
  { id: "run-1", taskId: "home-energy-upgrade-companion", status: "running", backend: "Hybrid API routing with municipal rules index", budgetUsd: 18000, runtimeHours: 220, checkpointCadenceHours: 24, reproducibilityNotes: "Each recommendation bundle stores source snapshots, usage assumptions, and confidence notes.", rollbackPlan: "Pause new recommendations, keep prior bundles visible, and route contested cases to manual review." },
  { id: "run-2", taskId: "repair-manual-finder", status: "complete", backend: "Search index plus lightweight OCR workers", budgetUsd: 5000, runtimeHours: 72, checkpointCadenceHours: 12, reproducibilityNotes: "Manual packets preserve source scans, model matches, and user corrections.", rollbackPlan: "Hide low-confidence matches and fall back to manual curation until OCR issues are resolved." },
  { id: "run-3", taskId: "benefit-appeal-packet-helper", status: "scheduled", backend: "Local rules index with supervised drafting", budgetUsd: 15000, runtimeHours: 168, checkpointCadenceHours: 24, reproducibilityNotes: "Draft packets preserve rule references, versions, and advocate edits.", rollbackPlan: "Stop packet generation immediately if rule freshness drops below the gate." },
  { id: "run-4", taskId: "local-air-quality-briefing", status: "running", backend: "Source monitoring mesh with alert deduplication", budgetUsd: 26000, runtimeHours: 720, checkpointCadenceHours: 12, reproducibilityNotes: "Briefings keep source IDs, alert timestamps, and local override notes for every region.", rollbackPlan: "Hold publication when sources disagree materially and switch to manual incident messaging." },
  { id: "run-5", taskId: "open-source-security-regression-watch", status: "running", backend: "Trusted CI runners plus isolated sandboxes", budgetUsd: 34000, runtimeHours: 720, checkpointCadenceHours: 12, reproducibilityNotes: "Every alert stores a replay bundle, failing case, and environment manifest.", rollbackPlan: "Mute a noisy signal, continue collection, and require human approval before any advisory is published." },
  { id: "run-6", taskId: "rare-disease-evidence-atlas", status: "running", backend: "Long-context retrieval and contradiction-preserving synthesis", budgetUsd: 38000, runtimeHours: 720, checkpointCadenceHours: 24, reproducibilityNotes: "The atlas retains source passages, contradiction markers, and revision history at each checkpoint.", rollbackPlan: "Freeze new syntheses, keep the latest validated atlas live, and route conflicts to domain review." },
  { id: "run-7", taskId: "clinic-follow-up-question-drafter", status: "complete", backend: "Retrieval-augmented drafting with clinician review queue", budgetUsd: 6200, runtimeHours: 72, checkpointCadenceHours: 12, reproducibilityNotes: "Drafted questions are stored with note excerpts, approvals, and rejection reasons.", rollbackPlan: "Disable clinic-facing drafting and retain the audit trail if clinicians see unsafe drift." },
  { id: "run-8", taskId: "museum-oral-history-indexer", status: "scheduled", backend: "Audio segmentation and metadata review pipeline", budgetUsd: 12000, runtimeHours: 144, checkpointCadenceHours: 24, reproducibilityNotes: "Every clip, speaker tag, and rights note links back to the original timecode and archive record.", rollbackPlan: "Stop public indexing if rights or attribution metadata becomes uncertain." },
];

export const seedCheckpoints: CheckpointRecord[] = [
  { id: "checkpoint-1", taskId: "home-energy-upgrade-companion", label: "Rule coverage gate", status: "complete", detail: "Verify rebate coverage and bill parsing across the first five pilot regions.", dueAt: "2026-03-07T18:00:00.000Z" },
  { id: "checkpoint-2", taskId: "home-energy-upgrade-companion", label: "Household pilot review", status: "active", detail: "Audit plan quality, confidence labels, and correction handling with partner nonprofits.", dueAt: "2026-03-19T18:00:00.000Z" },
  { id: "checkpoint-3", taskId: "benefit-appeal-packet-helper", label: "Rule freshness gate", status: "queued", detail: "Load the first jurisdiction bundle and confirm citation coverage before launch.", dueAt: "2026-03-21T10:00:00.000Z" },
  { id: "checkpoint-4", taskId: "benefit-appeal-packet-helper", label: "Advocate pilot gate", status: "queued", detail: "Review edits from partner advocates before releasing the second compute tranche.", dueAt: "2026-03-27T17:00:00.000Z" },
  { id: "checkpoint-5", taskId: "local-air-quality-briefing", label: "Coverage and freshness check", status: "complete", detail: "Confirm every region has enough source coverage and no stale notices leak into the digest.", dueAt: "2026-03-06T12:00:00.000Z" },
  { id: "checkpoint-6", taskId: "local-air-quality-briefing", label: "Public-language audit", status: "active", detail: "Review readability, source conflicts, and alert latency before expansion.", dueAt: "2026-03-21T12:00:00.000Z" },
  { id: "checkpoint-7", taskId: "open-source-security-regression-watch", label: "False-positive audit", status: "complete", detail: "Check alert precision and require replay bundles for each regression signal.", dueAt: "2026-03-08T14:00:00.000Z" },
  { id: "checkpoint-8", taskId: "open-source-security-regression-watch", label: "Embargo discipline gate", status: "active", detail: "Verify that embargoed details never spill into public outputs before approval.", dueAt: "2026-03-20T14:00:00.000Z" },
  { id: "checkpoint-9", taskId: "rare-disease-evidence-atlas", label: "Contradiction preservation gate", status: "complete", detail: "Confirm that the atlas preserves conflicting findings instead of flattening them.", dueAt: "2026-03-09T16:00:00.000Z" },
  { id: "checkpoint-10", taskId: "rare-disease-evidence-atlas", label: "Expert correction gate", status: "active", detail: "Review specialist edits and uncertainty labels before widening coverage.", dueAt: "2026-03-23T16:00:00.000Z" },
  { id: "checkpoint-11", taskId: "museum-oral-history-indexer", label: "Rights metadata gate", status: "queued", detail: "Confirm rights notes, speaker consent, and archive constraints before ingestion starts.", dueAt: "2026-03-24T11:00:00.000Z" },
  { id: "checkpoint-12", taskId: "clinic-follow-up-question-drafter", label: "Clinician pilot review", status: "complete", detail: "Measure whether suggested question sets are useful, safe, and easy to dismiss when wrong.", dueAt: "2026-03-04T15:00:00.000Z" },
];

export const seedGovernanceEvents: GovernanceEventRecord[] = [
  { id: "gov-1", taskId: "home-energy-upgrade-companion", house: "allocation-chamber", title: "Ken advanced into the active weeks lane", decision: "The chamber prioritized this Ken because it combines everyday usefulness with auditable source grounding.", outcome: "A week-scale lane opened with a nonprofit review checkpoint before wider rollout.", createdAt: "2026-03-04T18:00:00.000Z" },
  { id: "gov-2", taskId: "benefit-appeal-packet-helper", house: "safety-council", title: "Launch approved with advocate sign-off requirement", decision: "The council approved a narrow launch because the workflow drafts materials for advocates rather than replacing legal judgment.", outcome: "The Ken can launch once the rule-freshness gate and pilot sign-off are satisfied.", createdAt: "2026-03-12T19:00:00.000Z" },
  { id: "gov-3", taskId: "open-source-security-regression-watch", house: "safety-council", title: "Embargo handling constraints tightened", decision: "The council required explicit embargo handling before new public advisories can publish automatically.", outcome: "The Ken remains active, but public release stays gated behind stricter human review.", createdAt: "2026-03-11T13:30:00.000Z" },
  { id: "gov-4", taskId: "rare-disease-evidence-atlas", house: "allocation-chamber", title: "Month-scale compute retained after checkpoint review", decision: "The chamber renewed this Ken after specialist reviewers confirmed the contradiction log remained useful and source-grounded.", outcome: "Month-tier allocation stays live through the next expert correction checkpoint.", createdAt: "2026-03-10T20:00:00.000Z" },
  { id: "gov-5", taskId: "clinic-follow-up-question-drafter", house: "safety-council", title: "Pilot closed after compute limit with partial success", decision: "The council accepted a narrow shipped state because clinicians found the question drafts helpful, but broader automation remains premature.", outcome: "The pilot artifacts stay public while wider expansion returns to review.", createdAt: "2026-03-05T17:00:00.000Z" },
  { id: "gov-6", taskId: "autonomous-phishing-lure-optimizer", house: "safety-council", title: "Ken blocked as prohibited offensive work", decision: "The proposal directly improves phishing performance and cannot satisfy the platform's legitimacy or safety requirements.", outcome: "The Ken remains visible on the board as blocked and cannot collect compute allocation.", createdAt: "2026-03-03T11:00:00.000Z" },
  { id: "gov-7", taskId: null, house: "allocation-chamber", title: "Creative and cultural lane opened", decision: "A dedicated lane was added so the board does not collapse into purely utilitarian work.", outcome: "Creative and cultural Kens now rank directly inside their own category and allocation ladder.", createdAt: "2026-03-07T16:00:00.000Z" },
  { id: "gov-8", taskId: null, house: "safety-council", title: "Attestation ladder refined for public launch", decision: "The council separated identity confidence, sybil risk, and contribution standing in public profiles.", outcome: "Profiles now show verification source, review date, and sybil-risk band.", createdAt: "2026-03-14T15:00:00.000Z" },
];
