import type { CategoryRecord, CheckpointRecord, ComputeRunRecord, GovernanceEventRecord, ProfileRecord, TaskRecord, VoteRecord } from "@/lib/types";

export const seedProfiles: ProfileRecord[] = [
  { id: "maya-chen", username: "maintainer-reviewer-01", showRealName: false, name: "Maintainer Reviewer 01", role: "Open-source release reviewer", bio: "Reviews reproducible release evidence, dependency regressions, and rollback plans for public-interest software Kens.", specialty: "Release reliability", attestation: "Signed maintainer history and review", voiceCredits: 64, credibility: 0.95, avatarHue: 18 },
  { id: "noor-haddad", username: "evidence-curator-02", showRealName: false, name: "Evidence Curator 02", role: "Biomedical evidence curator", bio: "Checks source-grounded synthesis maps, contradiction logs, and expert-correction workflows for science and health Kens.", specialty: "Biomedical synthesis", attestation: "Publication and domain-review signals", voiceCredits: 82, credibility: 0.97, avatarHue: 152 },
  { id: "rafael-ortiz", username: "civic-systems-03", showRealName: false, name: "Civic Systems Reviewer 03", role: "Civic workflow reviewer", bio: "Evaluates public-service Kens for source freshness, local usefulness, accessibility, and non-extractive sponsor fit.", specialty: "Civic workflows", attestation: "Verified public-interest portfolio", voiceCredits: 54, credibility: 0.92, avatarHue: 206 },
  { id: "elena-petrov", username: "defensive-reviewer-04", showRealName: false, name: "Defensive Reviewer 04", role: "Defensive security reviewer", bio: "Reviews Kens that touch software supply chains, abuse boundaries, and reproducible incident evidence.", specialty: "Defensive operations", attestation: "Signed security maintainer attestations", voiceCredits: 38, credibility: 0.93, avatarHue: 340 },
  { id: "aiko-tanaka", username: "archive-tools-05", showRealName: false, name: "Archive Tools Reviewer 05", role: "Creative and cultural tools reviewer", bio: "Evaluates creative Kens for rights clarity, reusable artifacts, public access, and community-facing usefulness.", specialty: "Cultural tooling", attestation: "Portfolio review and references", voiceCredits: 46, credibility: 0.9, avatarHue: 276 },
  { id: "jordan-miles", username: "policy-workflow-06", showRealName: false, name: "Policy Workflow Reviewer 06", role: "Public-benefit workflow reviewer", bio: "Checks rules-heavy Kens for citation discipline, deadline handling, and clear human handoff instead of automated overreach.", specialty: "Rules and procurement", attestation: "Policy clinic review", voiceCredits: 31, credibility: 0.88, avatarHue: 44 },
  { id: "priya-singh", username: "clinic-ops-07", showRealName: false, name: "Clinic Ops Reviewer 07", role: "Operational pilot reviewer", bio: "Assesses whether clinic, research, and community workflows hold up in realistic pilot conditions.", specialty: "Operational review", attestation: "Independent consortium reference checks", voiceCredits: 51, credibility: 0.91, avatarHue: 118 },
];

export const seedCategories: CategoryRecord[] = [
  { id: "everyday-services", slug: "everyday-services", name: "Everyday Services", description: "Household, paperwork, repair, and money-saving Kens people would use in ordinary life.", thesis: "The strongest everyday Kens save people time, stress, and money by turning messy documents into clear next steps." },
  { id: "public-interest", slug: "public-interest", name: "Public Interest", description: "Community, climate, school, clinic, and public-service Kens with broad local value.", thesis: "Long-running AI earns trust when it keeps important local information fresh, source-linked, and easy to act on." },
  { id: "open-tools", slug: "open-tools", name: "Open Tools", description: "Reusable software, defensive tooling, and shared infrastructure other builders can build on.", thesis: "Some Kens matter because they make thousands of later fixes and public tools safer, cheaper, and easier." },
  { id: "science-health", slug: "science-health", name: "Science and Health", description: "Carefully supervised evidence maps and clinic support for under-resourced teams.", thesis: "Small labs and clinics usually need continuity, provenance, and correction loops more than another flashy demo." },
  { id: "creative-works", slug: "creative-works", name: "Creative and Cultural", description: "Creative, practical, and preservation-focused Kens for artists, educators, archives, and local groups.", thesis: "Creative and cultural work belongs here when it leaves behind tools, archives, and community value other people can reuse." },
];

export const seedTasks: TaskRecord[] = [
  { id: "home-energy-upgrade-companion", slug: "lab-protocol-reproduction-scout", categoryId: "science-health", proposerId: "noor-haddad", title: "Lab Protocol Reproduction Scout", summary: "Convert methods sections, reagent notes, and supplementary PDFs into a reproducibility map for small biology labs before they spend scarce bench time.", problem: "Many protocols fail because reagent substitutions, missing parameters, cell-line context, and tacit lab notes are scattered across papers and supplements.", whyNow: "Long-context, tool-using models can now keep a large protocol corpus active while retrieval and human checkpoints prevent confident hallucinated bench steps.", publicBenefit: "Gives small academic labs a source-linked way to spot protocol gaps, likely failure points, and missing controls before running costly experiments.", deliverables: ["Protocol dependency graph", "Reagent and parameter checklist", "Contradiction log with source snippets"], evaluationCriteria: ["Every protocol step links to a source passage", "Unresolved ambiguity is flagged instead of invented", "Domain reviewers can accept or reject each extracted dependency"], riskFlags: ["No wet-lab instructions beyond cited sources", "Human scientist review required before use"], evidence: ["Methods sections", "Supplementary tables", "Protocol repositories", "Reviewer correction notes"], requestedTier: "weeks", stage: "running", safetyStatus: "approved", budgetUsd: 18000, runtimeHours: 220, backend: "Long-context retrieval with structured extraction and reviewer gates", createdAt: "2026-04-16T09:00:00.000Z" },
  { id: "repair-manual-finder", slug: "open-source-regression-reproducer", categoryId: "open-tools", proposerId: "maya-chen", title: "Open-Source Regression Reproducer", summary: "Run agentic repro attempts for high-impact bug reports and publish minimal failing cases maintainers can actually review.", problem: "Maintainers receive vague breakage reports faster than they can reduce them to a reliable failing test, especially after dependency upgrades.", whyNow: "Modern coding agents can inspect repos, run tests, bisect changes, and propose compact repros when the workflow keeps logs, patches, and reviewer checks visible.", publicBenefit: "Helps shared software projects close regressions faster and leaves behind test cases downstream users can reuse.", deliverables: ["Minimal repro repository", "Bisect log", "Patch-ready failing test"], evaluationCriteria: ["Repro runs on a clean checkout", "Steps are deterministic", "Maintainers can reject noisy or unsafe automation output"], riskFlags: ["No automatic maintainer impersonation", "No undisclosed exploit detail"], evidence: ["Issue threads", "CI logs", "Dependency changelogs", "Maintainer review notes"], requestedTier: "days", stage: "shipped", safetyStatus: "approved", budgetUsd: 5000, runtimeHours: 72, backend: "Sandboxed coding agents with reproducible CI traces", createdAt: "2026-04-19T11:20:00.000Z" },
  { id: "benefit-appeal-packet-helper", slug: "grant-and-irb-deadline-copilot", categoryId: "public-interest", proposerId: "jordan-miles", title: "Grant and IRB Deadline Copilot", summary: "Turn dense funding calls, IRB checklists, and institutional instructions into source-linked task plans for under-resourced research teams.", problem: "Small labs often miss public-interest grants or ethics-document details because requirements live across PDFs, portals, emails, and institution-specific policies.", whyNow: "Frontier research models can maintain long instructions and draft structured checklists, but every claim must remain citation-bound and editable by the team.", publicBenefit: "Helps smaller research groups compete for funding and compliance without buying expensive grant-administration support.", deliverables: ["Requirement matrix", "Deadline calendar draft", "IRB document gap list"], evaluationCriteria: ["Every requirement cites source text", "Deadlines include timezone and portal assumptions", "No legal or compliance claim is presented as final advice"], riskFlags: ["Institution policies vary", "Human administrator review required"], evidence: ["Grant calls", "IRB templates", "University policy pages", "Portal screenshots"], requestedTier: "weeks", stage: "scheduled", safetyStatus: "approved", budgetUsd: 15000, runtimeHours: 168, backend: "Document-grounded planning agents with calendar export", createdAt: "2026-04-17T10:40:00.000Z" },
  { id: "small-town-procurement-checker", slug: "public-records-red-flag-reader", categoryId: "public-interest", proposerId: "jordan-miles", title: "Public Records Red-Flag Reader", summary: "Find contradictory dates, missing attachments, vendor lock-in language, and accessibility issues in public RFPs before release.", problem: "Small agencies and nonprofits publish complicated documents with limited review bandwidth, creating avoidable confusion and unequal access.", whyNow: "Document models can compare long solicitations against rules and prior templates, but the output must show exact source anchors and false-positive notes.", publicBenefit: "Makes public purchasing and grant documents easier to inspect, contest, and improve before mistakes become expensive.", deliverables: ["Issue log with anchors", "Plain-language correction suggestions", "Reviewer checklist"], evaluationCriteria: ["Flags quote the relevant source span", "Reviewers can mark false positives", "No output substitutes for legal advice"], riskFlags: ["No legal conclusion language", "Keep vendor accusations evidence-bound"], evidence: ["Public RFP archives", "Accessibility guidance", "Procurement templates", "Reviewer notes"], requestedTier: "days", stage: "voting", safetyStatus: "approved", budgetUsd: 5400, runtimeHours: 60, backend: "Structured document parser with rules and contrastive review", createdAt: "2026-04-20T14:10:00.000Z" },
  { id: "local-air-quality-briefing", slug: "wildfire-smoke-school-briefing", categoryId: "public-interest", proposerId: "rafael-ortiz", title: "Wildfire Smoke School Briefing", summary: "Maintain source-linked morning briefings for schools, clinics, and families when air-quality sensors, district notices, and public-health guidance disagree.", problem: "Smoke guidance is split across dashboards, district pages, weather alerts, and health sites that change faster than most families can follow.", whyNow: "Long-running monitoring agents can combine feeds and human overrides, but the value depends on clear provenance and conservative uncertainty labels.", publicBenefit: "Helps schools and clinics communicate practical, source-linked daily guidance without inventing medical advice.", deliverables: ["Morning briefing feed", "Source freshness dashboard", "Conflict and uncertainty labels"], evaluationCriteria: ["Source-to-brief latency stays below target", "Conflicting guidance is shown clearly", "Language is understandable to non-specialists"], riskFlags: ["No personalized health advice", "Escalate low sensor coverage"], evidence: ["EPA and local sensor feeds", "School district notices", "Public-health guidance", "Clinic review notes"], requestedTier: "months", stage: "running", safetyStatus: "approved", budgetUsd: 26000, runtimeHours: 720, backend: "Source monitoring mesh with human-readable provenance", createdAt: "2026-04-15T07:30:00.000Z" },
  { id: "open-source-security-regression-watch", slug: "supply-chain-regression-watch", categoryId: "open-tools", proposerId: "elena-petrov", title: "Supply-Chain Regression Watch", summary: "Continuously replay dependency test suites and publish defensive regression packets with rollback evidence, not vague security alarms.", problem: "Security-sensitive breakage often reaches downstream users because maintainers and consumers discover the same regression independently and too late.", whyNow: "Coding agents and sandboxed CI can now run longer replay jobs, but publication needs embargo controls, reproducible traces, and human approval.", publicBenefit: "Gives maintainers, registries, and downstream teams early defensive evidence they can reproduce and act on.", deliverables: ["Replay harness", "Regression evidence bundle", "Rollback-ready diff summary"], evaluationCriteria: ["Every alert links to a failing case", "False positives remain low", "Embargoed details are withheld until approved"], riskFlags: ["Never auto-publish exploit-enabling detail", "No automatic patch merge"], evidence: ["Dependency tests", "Security advisories", "Maintainer threads", "Downstream incident reports"], requestedTier: "months", stage: "running", safetyStatus: "monitor", budgetUsd: 34000, runtimeHours: 720, backend: "Trusted CI runners plus isolated agent sandboxes", createdAt: "2026-04-15T12:00:00.000Z" },
  { id: "rare-disease-evidence-atlas", slug: "rare-disease-evidence-atlas", categoryId: "science-health", proposerId: "noor-haddad", title: "Rare Disease Evidence Atlas", summary: "Maintain a living map of hypotheses, interventions, contradictions, trial signals, and open questions for understudied conditions.", problem: "Patient foundations and small research teams rarely have enough staff to keep a rigorous synthesis map current as papers, preprints, and registries change.", whyNow: "Frontier long-context models can preserve competing explanations over time if citations, uncertainty labels, and expert correction checkpoints come first.", publicBenefit: "Gives small labs and patient communities a continuously updated evidence surface instead of another static PDF review.", deliverables: ["Source-grounded evidence map", "Contradiction and uncertainty log", "Priority questions for follow-up"], evaluationCriteria: ["Claims preserve uncertainty", "Every entry cites source text", "Experts can submit corrections efficiently"], riskFlags: ["No clinical recommendation claims", "Separate hypotheses from established evidence"], evidence: ["PubMed and preprint feeds", "Trial registries", "Foundation reports", "Expert correction notes"], requestedTier: "months", stage: "running", safetyStatus: "approved", budgetUsd: 38000, runtimeHours: 720, backend: "Long-context retrieval and contradiction-preserving synthesis", createdAt: "2026-04-16T09:10:00.000Z" },
  { id: "clinic-follow-up-question-drafter", slug: "clinic-note-follow-up-triage", categoryId: "science-health", proposerId: "priya-singh", title: "Clinic Note Follow-Up Triage", summary: "Draft source-linked follow-up questions for community clinics after dense specialist notes, lab summaries, and care plans arrive.", problem: "Small clinics receive long specialist documents without enough staff time to extract concrete follow-up questions and uncertainty flags.", whyNow: "Models can summarize long clinical documents, but safe usefulness requires narrow scope, traceable source snippets, and clinician sign-off.", publicBenefit: "Improves continuity of care in under-resourced settings without claiming diagnosis or replacing medical judgment.", deliverables: ["Question set draft", "Source-linked note summary", "Escalation flags for clinician review"], evaluationCriteria: ["Clinicians can audit each question", "Unsafe suggestions are rare", "Rejected outputs improve future checks"], riskFlags: ["No diagnosis or treatment automation", "Human sign-off required"], evidence: ["Specialist note templates", "Clinic follow-up protocols", "Quality-improvement reviews"], requestedTier: "days", stage: "shipped", safetyStatus: "monitor", budgetUsd: 6200, runtimeHours: 72, backend: "Retrieval-augmented drafting with clinician review queue", createdAt: "2026-04-20T15:30:00.000Z" },
  { id: "museum-oral-history-indexer", slug: "oral-history-multimodal-index", categoryId: "creative-works", proposerId: "aiko-tanaka", title: "Oral History Multimodal Index", summary: "Turn long interviews, photos, and archive notes into searchable, timestamped, rights-aware story maps for local museums and schools.", problem: "Small archives record valuable interviews but cannot afford transcription cleanup, speaker segmentation, metadata repair, and rights review.", whyNow: "Multimodal models can connect audio, images, and documents, but archives still need careful consent notes and public/private boundaries.", publicBenefit: "Makes local history collections discoverable for educators, families, artists, and future researchers.", deliverables: ["Searchable transcript timeline", "Rights and consent notes", "Topic-linked exhibit snippets"], evaluationCriteria: ["Quotes align to timestamps", "Archives can correct metadata easily", "Restricted material is excluded from public output"], riskFlags: ["Consent rules vary", "Preserve speaker context"], evidence: ["Interview recordings", "Archive metadata", "Rights agreements", "Educator feedback"], requestedTier: "weeks", stage: "scheduled", safetyStatus: "approved", budgetUsd: 12000, runtimeHours: 144, backend: "Multimodal segmentation and metadata review pipeline", createdAt: "2026-04-18T13:45:00.000Z" },
  { id: "public-domain-performance-studio", slug: "public-domain-remix-studio", categoryId: "creative-works", proposerId: "aiko-tanaka", title: "Public-Domain Remix Studio", summary: "Help educators, game designers, and community theaters turn public-domain material into rights-safe scripts, scenes, maps, and classroom assets.", problem: "Creative groups waste time rediscovering what they can legally reuse and how to convert old material into practical, editable production packets.", whyNow: "Creative AI tools are popular, but public-interest creative workflows need provenance, rights checks, and reusable artifacts rather than disposable images.", publicBenefit: "Supports arts access, teaching, preservation, and functional creative tools for groups without production staff.", deliverables: ["Rights-safe source finder", "Editable production packet", "Scene, map, or asset breakdown"], evaluationCriteria: ["Every source is public-domain or clearly licensed", "Outputs remain editable", "Users can trace source provenance"], riskFlags: ["Avoid false rights claims", "Human review before public release"], evidence: ["Public-domain repositories", "Library scans", "Production planning templates", "Rights metadata"], requestedTier: "days", stage: "voting", safetyStatus: "approved", budgetUsd: 4800, runtimeHours: 54, backend: "Archive search plus structured creative workflow", createdAt: "2026-04-21T12:25:00.000Z" },
  { id: "autonomous-phishing-lure-optimizer", slug: "autonomous-exploit-agent-optimizer", categoryId: "open-tools", proposerId: "maya-chen", title: "Autonomous Exploit Agent Optimizer", summary: "Continuously improve offensive exploit chains, phishing copy, evasion tactics, and target-specific automation.", problem: "The Ken directly increases offensive abuse capacity and would help attackers scale harm.", whyNow: "It should not launch.", publicBenefit: "None established.", deliverables: ["Not applicable"], evaluationCriteria: ["Not applicable"], riskFlags: ["Credential theft enablement", "Exploit automation", "Evasion optimization"], evidence: ["Safety review filing"], requestedTier: "months", stage: "blocked", safetyStatus: "blocked", budgetUsd: 0, runtimeHours: 0, backend: "Denied", createdAt: "2026-04-18T18:00:00.000Z" },
  { id: "school-lunch-menu-translator", slug: "school-menu-allergen-translator", categoryId: "everyday-services", proposerId: "priya-singh", title: "School Menu Allergen Translator", summary: "Translate school menus, allergen notes, and free-meal forms into clear family-facing packets with source-linked uncertainty flags.", problem: "Families still receive nutrition and benefits documents as dense English-only PDFs with technical allergen language and unclear deadlines.", whyNow: "Multilingual models are strong enough for draft translation, but public use needs native-speaker review, source snapshots, and conservative risk labels.", publicBenefit: "Helps families understand meal options and access benefits without treating the demo as an official district form.", deliverables: ["Translated menu pack", "Allergen flag sheet", "Free-meal form explainer"], evaluationCriteria: ["Translations get native-speaker review", "Allergen flags match source records", "Official forms remain clearly distinguished"], riskFlags: ["Translation accuracy varies", "No replacement for official district notices"], evidence: ["District menu PDFs", "USDA allergen references", "Multilingual school communication samples"], requestedTier: "days", stage: "voting", safetyStatus: "approved", budgetUsd: 4200, runtimeHours: 48, backend: "Multilingual document pipeline with human review", createdAt: "2026-04-22T09:00:00.000Z" },
  { id: "neighborhood-pothole-tracker", slug: "city-permitting-queue-monitor", categoryId: "public-interest", proposerId: "rafael-ortiz", title: "City Permitting Queue Monitor", summary: "Compare public permit records, meeting notes, and status portals so residents can see where projects are delayed or missing required updates.", problem: "Residents and small businesses often cannot tell whether a permit is waiting on applicants, agencies, hearings, or missing public records.", whyNow: "Long-running agents can monitor open data and meeting artifacts, but public trust depends on showing exact source timestamps and uncertainty.", publicBenefit: "Makes local government processes easier to understand without accusing staff or fabricating status.", deliverables: ["Public status timeline", "Missing-update detector", "Source timestamp ledger"], evaluationCriteria: ["Records match official sources", "Status claims include timestamps", "Uncertain cases are labeled"], riskFlags: ["Do not infer corruption", "Do not expose private applicant data"], evidence: ["Permit portals", "Meeting minutes", "Open-data feeds", "Public notices"], requestedTier: "weeks", stage: "review", safetyStatus: "pending", budgetUsd: 9800, runtimeHours: 120, backend: "Open data ingestion with source timestamp reconciliation", createdAt: "2026-04-23T14:00:00.000Z" },
  { id: "freelancer-invoice-checker", slug: "research-dataset-license-auditor", categoryId: "open-tools", proposerId: "maya-chen", title: "Research Dataset License Auditor", summary: "Scan README files, dataset cards, citations, and repository history to flag unclear reuse rights before labs publish or build on a dataset.", problem: "Research datasets often mix licenses, scraped sources, model outputs, and missing provenance, creating downstream risk for open tools and academic reuse.", whyNow: "Modern code and document models can inspect repositories and metadata at scale, but the output must remain conservative and reviewable.", publicBenefit: "Helps researchers publish cleaner datasets and helps builders avoid accidental misuse of ambiguous data.", deliverables: ["License conflict report", "Provenance gap checklist", "Public dataset-card patch suggestions"], evaluationCriteria: ["Each flag cites a file or source", "Reviewers can dismiss false positives", "No legal advice is implied"], riskFlags: ["Not legal advice", "Private data must not be ingested"], evidence: ["Dataset cards", "README files", "Repository history", "License texts"], requestedTier: "days", stage: "voting", safetyStatus: "approved", budgetUsd: 3800, runtimeHours: 36, backend: "Repository agent with license and provenance rules", createdAt: "2026-04-24T10:30:00.000Z" },
];

export const seedVotes: VoteRecord[] = [
  { id: "vote-1", taskId: "home-energy-upgrade-companion", profileId: "noor-haddad", voteCount: 6, rationale: "A strong fit for sustained compute because protocol ambiguity needs citation-preserving iteration.", updatedAt: "2026-04-25T09:00:00.000Z" },
  { id: "vote-2", taskId: "home-energy-upgrade-companion", profileId: "priya-singh", voteCount: 4, rationale: "Useful to small labs if every extracted step remains reviewable and conservative.", updatedAt: "2026-04-25T09:08:00.000Z" },
  { id: "vote-3", taskId: "local-air-quality-briefing", profileId: "rafael-ortiz", voteCount: 7, rationale: "Public-health communication is valuable when source freshness and uncertainty stay visible.", updatedAt: "2026-04-25T09:12:00.000Z" },
  { id: "vote-4", taskId: "local-air-quality-briefing", profileId: "priya-singh", voteCount: 4, rationale: "Direct operational value for schools, clinics, and families during fast-moving events.", updatedAt: "2026-04-25T09:18:00.000Z" },
  { id: "vote-5", taskId: "benefit-appeal-packet-helper", profileId: "jordan-miles", voteCount: 5, rationale: "Deadline and requirement extraction is exactly where source-bound agents can help small teams.", updatedAt: "2026-04-25T09:24:00.000Z" },
  { id: "vote-6", taskId: "benefit-appeal-packet-helper", profileId: "noor-haddad", voteCount: 3, rationale: "Good bridge between academic research overhead and public-interest funding access.", updatedAt: "2026-04-25T09:26:00.000Z" },
  { id: "vote-7", taskId: "open-source-security-regression-watch", profileId: "elena-petrov", voteCount: 8, rationale: "Shared defensive infrastructure compounds across many projects if embargo handling is strict.", updatedAt: "2026-04-25T09:31:00.000Z" },
  { id: "vote-8", taskId: "open-source-security-regression-watch", profileId: "maya-chen", voteCount: 5, rationale: "Replay bundles and rollback evidence are concrete outputs maintainers can inspect.", updatedAt: "2026-04-25T09:33:00.000Z" },
  { id: "vote-9", taskId: "rare-disease-evidence-atlas", profileId: "noor-haddad", voteCount: 7, rationale: "Continuity and contradiction handling are the real value here.", updatedAt: "2026-04-25T09:38:00.000Z" },
  { id: "vote-10", taskId: "rare-disease-evidence-atlas", profileId: "priya-singh", voteCount: 5, rationale: "A living evidence map is more useful than another static review for small patient communities.", updatedAt: "2026-04-25T09:41:00.000Z" },
  { id: "vote-11", taskId: "museum-oral-history-indexer", profileId: "aiko-tanaka", voteCount: 4, rationale: "Small archives need rights-aware multimodal workflow, not one-off transcription.", updatedAt: "2026-04-25T09:44:00.000Z" },
  { id: "vote-12", taskId: "repair-manual-finder", profileId: "maya-chen", voteCount: 3, rationale: "Fast public value because maintainers can verify or reject a minimal repro quickly.", updatedAt: "2026-04-25T09:47:00.000Z" },
  { id: "vote-13", taskId: "clinic-follow-up-question-drafter", profileId: "priya-singh", voteCount: 2, rationale: "Worth running narrowly with strong clinician oversight and explicit rejection logging.", updatedAt: "2026-04-25T09:50:00.000Z" },
  { id: "vote-14", taskId: "public-domain-performance-studio", profileId: "aiko-tanaka", voteCount: 3, rationale: "Creative work belongs here when provenance, rights, and reusable artifacts are central.", updatedAt: "2026-04-25T09:55:00.000Z" },
  { id: "vote-15", taskId: "school-lunch-menu-translator", profileId: "priya-singh", voteCount: 4, rationale: "Families should not miss meal access because the forms are unreadable.", updatedAt: "2026-04-25T10:00:00.000Z" },
  { id: "vote-16", taskId: "school-lunch-menu-translator", profileId: "jordan-miles", voteCount: 3, rationale: "Simple, high-impact, and bounded if official documents stay clearly distinguished.", updatedAt: "2026-04-25T10:02:00.000Z" },
  { id: "vote-17", taskId: "neighborhood-pothole-tracker", profileId: "rafael-ortiz", voteCount: 5, rationale: "A source-timestamped permitting monitor would be genuinely useful without overclaiming.", updatedAt: "2026-04-25T10:05:00.000Z" },
  { id: "vote-18", taskId: "freelancer-invoice-checker", profileId: "maya-chen", voteCount: 3, rationale: "Dataset provenance and license review is high-leverage open infrastructure.", updatedAt: "2026-04-25T10:08:00.000Z" },
  { id: "vote-19", taskId: "freelancer-invoice-checker", profileId: "jordan-miles", voteCount: 2, rationale: "Clear public benefit if the output stays conservative and non-legal-advice.", updatedAt: "2026-04-25T10:10:00.000Z" },
];

export const seedRuns: ComputeRunRecord[] = [
  { id: "run-1", taskId: "home-energy-upgrade-companion", status: "running", backend: "Long-context retrieval with structured extraction and reviewer gates", budgetUsd: 18000, runtimeHours: 220, checkpointCadenceHours: 24, reproducibilityNotes: "Each extracted step stores source snippets, model traces, reviewer decisions, and unresolved ambiguity labels.", rollbackPlan: "Freeze new protocol packets, keep reviewed packets visible, and route contested extraction to domain reviewers." },
  { id: "run-2", taskId: "repair-manual-finder", status: "complete", backend: "Sandboxed coding agents with reproducible CI traces", budgetUsd: 5000, runtimeHours: 72, checkpointCadenceHours: 12, reproducibilityNotes: "Repro packets preserve clean checkout, dependency versions, terminal logs, failing test, and maintainer feedback.", rollbackPlan: "Hide noisy repros and fall back to manual curation until deterministic runs clear review." },
  { id: "run-3", taskId: "benefit-appeal-packet-helper", status: "scheduled", backend: "Document-grounded planning agents with calendar export", budgetUsd: 15000, runtimeHours: 168, checkpointCadenceHours: 24, reproducibilityNotes: "Requirement matrices preserve source spans, portal assumptions, deadline calculations, and reviewer edits.", rollbackPlan: "Stop plan generation immediately if source freshness or requirement extraction drops below the gate." },
  { id: "run-4", taskId: "local-air-quality-briefing", status: "running", backend: "Source monitoring mesh with human-readable provenance", budgetUsd: 26000, runtimeHours: 720, checkpointCadenceHours: 12, reproducibilityNotes: "Briefings keep source IDs, timestamps, conflict labels, and local override notes for every region.", rollbackPlan: "Hold publication when sources disagree materially and switch to manual incident messaging." },
  { id: "run-5", taskId: "open-source-security-regression-watch", status: "running", backend: "Trusted CI runners plus isolated agent sandboxes", budgetUsd: 34000, runtimeHours: 720, checkpointCadenceHours: 12, reproducibilityNotes: "Every alert stores a replay bundle, failing case, environment manifest, and publication gate status.", rollbackPlan: "Mute noisy signals, continue collection, and require human approval before any advisory is published." },
  { id: "run-6", taskId: "rare-disease-evidence-atlas", status: "running", backend: "Long-context retrieval and contradiction-preserving synthesis", budgetUsd: 38000, runtimeHours: 720, checkpointCadenceHours: 24, reproducibilityNotes: "The atlas retains source passages, contradiction markers, expert corrections, and revision history at each checkpoint.", rollbackPlan: "Freeze new syntheses, keep the latest validated atlas live, and route conflicts to domain review." },
  { id: "run-7", taskId: "clinic-follow-up-question-drafter", status: "complete", backend: "Retrieval-augmented drafting with clinician review queue", budgetUsd: 6200, runtimeHours: 72, checkpointCadenceHours: 12, reproducibilityNotes: "Drafted questions are stored with note excerpts, approvals, rejections, and clinician comments.", rollbackPlan: "Disable clinic-facing drafting and retain the audit trail if clinicians see unsafe drift." },
  { id: "run-8", taskId: "museum-oral-history-indexer", status: "scheduled", backend: "Multimodal segmentation and metadata review pipeline", budgetUsd: 12000, runtimeHours: 144, checkpointCadenceHours: 24, reproducibilityNotes: "Every clip, speaker tag, image reference, and rights note links back to timecode and archive metadata.", rollbackPlan: "Stop public indexing if rights or attribution metadata becomes uncertain." },
  { id: "run-9", taskId: "school-lunch-menu-translator", status: "scheduled" as const, backend: "Multilingual document pipeline with human review", budgetUsd: 4200, runtimeHours: 48, checkpointCadenceHours: 12, reproducibilityNotes: "Each translated menu pack stores source PDF, translation model, native-speaker review status, and official-form boundary notes.", rollbackPlan: "Halt translations and fall back to original district documents if review accuracy drops below threshold." },
];

export const seedCheckpoints: CheckpointRecord[] = [
  { id: "checkpoint-1", taskId: "home-energy-upgrade-companion", label: "Source extraction gate", status: "complete", detail: "Verify that protocol steps, reagents, and parameters cite exact source passages before reviewer expansion.", dueAt: "2026-04-20T18:00:00.000Z" },
  { id: "checkpoint-2", taskId: "home-energy-upgrade-companion", label: "Domain reviewer gate", status: "active", detail: "Audit ambiguity labels and reject any inferred bench step without an explicit source.", dueAt: "2026-04-27T18:00:00.000Z" },
  { id: "checkpoint-3", taskId: "benefit-appeal-packet-helper", label: "Requirement freshness gate", status: "queued", detail: "Load the first funding-call and IRB bundle and confirm citation coverage before launch.", dueAt: "2026-04-29T10:00:00.000Z" },
  { id: "checkpoint-4", taskId: "benefit-appeal-packet-helper", label: "Research admin pilot gate", status: "queued", detail: "Review task-plan edits from research administrators before releasing the second compute tranche.", dueAt: "2026-05-02T17:00:00.000Z" },
  { id: "checkpoint-5", taskId: "local-air-quality-briefing", label: "Coverage and freshness check", status: "complete", detail: "Confirm every region has enough source coverage and no stale notices leak into the briefing.", dueAt: "2026-04-18T12:00:00.000Z" },
  { id: "checkpoint-6", taskId: "local-air-quality-briefing", label: "Public-language audit", status: "active", detail: "Review readability, source conflicts, and alert latency before district expansion.", dueAt: "2026-04-28T12:00:00.000Z" },
  { id: "checkpoint-7", taskId: "open-source-security-regression-watch", label: "False-positive audit", status: "complete", detail: "Check alert precision and require replay bundles for each regression signal.", dueAt: "2026-04-19T14:00:00.000Z" },
  { id: "checkpoint-8", taskId: "open-source-security-regression-watch", label: "Embargo discipline gate", status: "active", detail: "Verify that embargoed details never spill into public outputs before approval.", dueAt: "2026-04-30T14:00:00.000Z" },
  { id: "checkpoint-9", taskId: "rare-disease-evidence-atlas", label: "Contradiction preservation gate", status: "complete", detail: "Confirm that the atlas preserves conflicting findings instead of flattening them.", dueAt: "2026-04-20T16:00:00.000Z" },
  { id: "checkpoint-10", taskId: "rare-disease-evidence-atlas", label: "Expert correction gate", status: "active", detail: "Review specialist edits and uncertainty labels before widening coverage.", dueAt: "2026-05-01T16:00:00.000Z" },
  { id: "checkpoint-11", taskId: "museum-oral-history-indexer", label: "Rights metadata gate", status: "queued", detail: "Confirm rights notes, speaker consent, image constraints, and archive boundaries before ingestion starts.", dueAt: "2026-05-03T11:00:00.000Z" },
  { id: "checkpoint-12", taskId: "clinic-follow-up-question-drafter", label: "Clinician pilot review", status: "complete", detail: "Measure whether suggested question sets were useful, safe, and easy to dismiss when wrong.", dueAt: "2026-04-24T15:00:00.000Z" },
  { id: "checkpoint-13", taskId: "school-lunch-menu-translator", label: "Translation accuracy gate", status: "queued" as const, detail: "Verify translations against native-speaker reviews for the three most common non-English languages in partner districts.", dueAt: "2026-04-30T12:00:00.000Z" },
];

export const seedGovernanceEvents: GovernanceEventRecord[] = [
  { id: "gov-1", taskId: "home-energy-upgrade-companion", house: "allocation-chamber", title: "Protocol scout advanced into the weeks lane", decision: "The chamber prioritized the Ken because small labs get concrete value only if extraction, ambiguity, and reviewer correction run longer than a one-shot prompt.", outcome: "A week-scale lane opened with a domain-review checkpoint before wider protocol coverage.", createdAt: "2026-04-21T18:00:00.000Z" },
  { id: "gov-2", taskId: "benefit-appeal-packet-helper", house: "safety-council", title: "Launch approved with research-admin sign-off", decision: "The council approved a narrow launch because the workflow drafts requirements and deadlines for human review rather than claiming compliance authority.", outcome: "The Ken can launch once the requirement-freshness gate and pilot sign-off are satisfied.", createdAt: "2026-04-22T19:00:00.000Z" },
  { id: "gov-3", taskId: "open-source-security-regression-watch", house: "safety-council", title: "Embargo handling constraints tightened", decision: "The council required explicit embargo handling before any public advisory can publish from an agent-generated replay packet.", outcome: "The Ken remains active, but public release stays gated behind stricter human review.", createdAt: "2026-04-23T13:30:00.000Z" },
  { id: "gov-4", taskId: "rare-disease-evidence-atlas", house: "allocation-chamber", title: "Month-scale evidence atlas retained after checkpoint review", decision: "The chamber renewed this Ken after reviewers confirmed contradiction labels remained useful, source-grounded, and easy to contest.", outcome: "Month-tier allocation stays live through the next expert correction checkpoint.", createdAt: "2026-04-24T20:00:00.000Z" },
  { id: "gov-5", taskId: "clinic-follow-up-question-drafter", house: "safety-council", title: "Clinic triage pilot closed at limit with partial success", decision: "The council accepted a narrow shipped state because clinicians kept some question drafts, but broader automation remains premature.", outcome: "The pilot artifacts stay public while expansion returns to review.", createdAt: "2026-04-24T17:00:00.000Z" },
  { id: "gov-6", taskId: "autonomous-phishing-lure-optimizer", house: "safety-council", title: "Exploit-optimization Ken blocked as prohibited work", decision: "The proposal directly improves offensive abuse capacity and cannot satisfy the platform's legitimacy or safety requirements.", outcome: "The Ken remains visible as blocked and cannot collect compute allocation or sponsorship.", createdAt: "2026-04-19T11:00:00.000Z" },
  { id: "gov-7", taskId: null, house: "allocation-chamber", title: "Creative and cultural lane retained", decision: "The lane remains because rights-safe creative tooling, archives, games, and public-domain workflows create public value beyond strictly utilitarian tasks.", outcome: "Creative and cultural Kens rank inside their own category and allocation ladder.", createdAt: "2026-04-20T16:00:00.000Z" },
  { id: "gov-8", taskId: null, house: "safety-council", title: "Public profiles moved away from filler names", decision: "The council recommended pseudonymous sandbox reviewers so demo accounts do not look like real public contributors.", outcome: "Seeded reviewer profiles now show role-based handles, verification source, review date, and sybil-risk band.", createdAt: "2026-04-25T15:00:00.000Z" },
  { id: "gov-9", taskId: "neighborhood-pothole-tracker", house: "safety-council" as const, title: "Permit monitor queued for source-accuracy review", decision: "The council wants to confirm public records are fresh and that the monitor does not infer misconduct or expose private applicant data.", outcome: "The Ken can collect public signal while the data freshness review is underway.", createdAt: "2026-04-25T14:30:00.000Z" },
];
