import type {
  CheckpointGateRecord,
  CommentRecord,
  CommentVoteRecord,
  RevenueStreamRecord,
  TaskFinanceRecord,
  TaskPulseVoteRecord,
  TreasuryEntryRecord,
} from "@/lib/types";

export const seedTaskFinance: TaskFinanceRecord[] = [
  {
    taskId: "critical-oss-regression-radar",
    qualityBondCredits: 5,
    sponsorPoolUsd: 18000,
    checkpointApprovalTarget: 28,
    enterprisePackaging: "Managed release intelligence API for CI, package registries, and downstream teams.",
    dataValueNote: "Regression adjudications and maintainer corrections form premium preference data for eval loops.",
  },
  {
    taskId: "multi-model-agent-eval-harness",
    qualityBondCredits: 4,
    sponsorPoolUsd: 22000,
    checkpointApprovalTarget: 24,
    enterprisePackaging: "Benchmark-as-a-service with sealed manifests, cost reports, and routing scorecards.",
    dataValueNote: "Cross-model preference traces create licensable evaluation and routing data.",
  },
  {
    taskId: "dependency-incident-war-room",
    qualityBondCredits: 4,
    sponsorPoolUsd: 14000,
    checkpointApprovalTarget: 18,
    enterprisePackaging: "Embargo-safe advisory workspace for security vendors and platform teams.",
    dataValueNote: "Defensive triage corrections improve severity alignment and incident routing datasets.",
  },
  {
    taskId: "decentralized-gpu-benchmarking-harness",
    qualityBondCredits: 3,
    sponsorPoolUsd: 16000,
    checkpointApprovalTarget: 22,
    enterprisePackaging: "Reliability intelligence feed for procurement teams and neutral schedulers.",
    dataValueNote: "Restart traces and fraud labels create supply-side quality data for compute markets.",
  },
  {
    taskId: "patch-review-triage-copilot",
    qualityBondCredits: 2,
    sponsorPoolUsd: 9000,
    checkpointApprovalTarget: 12,
    enterprisePackaging: "Maintainer workflow copilot with queue analytics and SLA reporting.",
    dataValueNote: "Reviewer preference signals can train ranking and explanation systems.",
  },
  {
    taskId: "long-context-open-weights-routing-bench",
    qualityBondCredits: 2,
    sponsorPoolUsd: 10000,
    checkpointApprovalTarget: 16,
    enterprisePackaging: "Routing consultant package for teams mixing APIs, open weights, and spot GPUs.",
    dataValueNote: "Economic routing traces become a reusable pricing and substitution dataset.",
  },
  {
    taskId: "grant-writing-research-assistant",
    qualityBondCredits: 2,
    sponsorPoolUsd: 8000,
    checkpointApprovalTarget: 12,
    enterprisePackaging: "Grant-ops workflow for small labs and translational nonprofits.",
    dataValueNote: "Acceptance and revision patterns produce premium proposal-quality feedback data.",
  },
  {
    taskId: "translation-workbench-for-disaster-ops",
    qualityBondCredits: 2,
    sponsorPoolUsd: 6000,
    checkpointApprovalTarget: 10,
    enterprisePackaging: "Reviewed multilingual emergency operations desk with audit trails.",
    dataValueNote: "Reviewer edits create terminology and preference datasets for critical translation loops.",
  },
  {
    taskId: "maintainer-sustainability-forecast",
    qualityBondCredits: 2,
    sponsorPoolUsd: 5000,
    checkpointApprovalTarget: 10,
    enterprisePackaging: "Health monitoring add-on for foundations supporting critical dependencies.",
    dataValueNote: "Contestable interventions and overrides create nuanced governance preference data.",
  },
  {
    taskId: "privacy-first-citation-graph",
    qualityBondCredits: 2,
    sponsorPoolUsd: 7500,
    checkpointApprovalTarget: 10,
    enterprisePackaging: "Enterprise provenance layer with privacy-preserving evidence bundles.",
    dataValueNote: "Signed provenance adjudications become high-value supervision data for grounded systems.",
  },
  {
    taskId: "reproducible-dataset-pipeline",
    qualityBondCredits: 1,
    sponsorPoolUsd: 4000,
    checkpointApprovalTarget: 8,
    enterprisePackaging: "Managed dataset build service for labs that need reproducibility without extra headcount.",
    dataValueNote: "Data cleaning decisions create reusable alignment data for tool-using agents.",
  },
  {
    taskId: "civic-procurement-spec-checker",
    qualityBondCredits: 1,
    sponsorPoolUsd: 4500,
    checkpointApprovalTarget: 8,
    enterprisePackaging: "Public-sector procurement linting product with plain-language rewrite workflows.",
    dataValueNote: "Correction histories form a public-interest drafting and preference dataset.",
  },
  {
    taskId: "autonomous-exploit-kit-tuner",
    qualityBondCredits: 5,
    sponsorPoolUsd: 0,
    checkpointApprovalTarget: 0,
    enterprisePackaging: "Ineligible for commercialization because the task is blocked as prohibited dual-use work.",
    dataValueNote: "No dataset generation or revenue extraction is permitted for blocked offensive work.",
  },
  {
    taskId: "local-air-quality-alert-compiler",
    qualityBondCredits: 3,
    sponsorPoolUsd: 12000,
    checkpointApprovalTarget: 20,
    enterprisePackaging: "Civic alerting dashboard for clinics, schools, and municipal operations.",
    dataValueNote: "Source-ranked alert corrections create preference data for public-health triage workflows.",
  },
  {
    taskId: "benefit-appeals-document-navigator",
    qualityBondCredits: 3,
    sponsorPoolUsd: 15000,
    checkpointApprovalTarget: 18,
    enterprisePackaging: "Managed appeals preparation workflow for legal aid clinics and caseworkers.",
    dataValueNote: "Human edits to rule-grounded packets create exceptional high-signal preference data.",
  },
  {
    taskId: "municipal-budget-red-flag-monitor",
    qualityBondCredits: 2,
    sponsorPoolUsd: 9000,
    checkpointApprovalTarget: 14,
    enterprisePackaging: "Budget diagnostic feed for local newsrooms, watchdog groups, and municipal advisors.",
    dataValueNote: "Community corrections produce explainability data for fiscal anomaly detection.",
  },
  {
    taskId: "rare-disease-literature-mapper",
    qualityBondCredits: 4,
    sponsorPoolUsd: 20000,
    checkpointApprovalTarget: 24,
    enterprisePackaging: "Research atlas product for foundations, small biotechs, and clinician-scientist teams.",
    dataValueNote: "Expert contradiction handling yields frontier preference data for biomedical synthesis systems.",
  },
  {
    taskId: "open-materials-discovery-notebook",
    qualityBondCredits: 3,
    sponsorPoolUsd: 11000,
    checkpointApprovalTarget: 16,
    enterprisePackaging: "Hypothesis-tracking notebook for small materials labs and translational teams.",
    dataValueNote: "Experiment prioritization and rejection data improve long-horizon scientific planning agents.",
  },
  {
    taskId: "public-domain-storyworld-builder",
    qualityBondCredits: 1,
    sponsorPoolUsd: 3000,
    checkpointApprovalTarget: 6,
    enterprisePackaging: "Rights-safe archive research assistant for studios, museums, and educators.",
    dataValueNote: "Archive selection and provenance review create reusable cultural curation data.",
  },
];

export const seedTaskPulseVotes: TaskPulseVoteRecord[] = [
  { id: "pulse-1", taskId: "critical-oss-regression-radar", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T09:00:00.000Z" },
  { id: "pulse-2", taskId: "critical-oss-regression-radar", profileId: "noor-haddad", value: 1, updatedAt: "2026-03-15T09:03:00.000Z" },
  { id: "pulse-3", taskId: "critical-oss-regression-radar", profileId: "elena-petrov", value: 1, updatedAt: "2026-03-15T09:05:00.000Z" },
  { id: "pulse-4", taskId: "multi-model-agent-eval-harness", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T09:08:00.000Z" },
  { id: "pulse-5", taskId: "multi-model-agent-eval-harness", profileId: "aiko-tanaka", value: 1, updatedAt: "2026-03-15T09:11:00.000Z" },
  { id: "pulse-6", taskId: "multi-model-agent-eval-harness", profileId: "noor-haddad", value: 1, updatedAt: "2026-03-15T09:13:00.000Z" },
  { id: "pulse-7", taskId: "dependency-incident-war-room", profileId: "elena-petrov", value: 1, updatedAt: "2026-03-15T09:15:00.000Z" },
  { id: "pulse-8", taskId: "dependency-incident-war-room", profileId: "priya-singh", value: 1, updatedAt: "2026-03-15T09:17:00.000Z" },
  { id: "pulse-9", taskId: "long-context-open-weights-routing-bench", profileId: "aiko-tanaka", value: 1, updatedAt: "2026-03-15T09:20:00.000Z" },
  { id: "pulse-10", taskId: "grant-writing-research-assistant", profileId: "aiko-tanaka", value: 1, updatedAt: "2026-03-15T09:21:00.000Z" },
  { id: "pulse-11", taskId: "grant-writing-research-assistant", profileId: "rafael-ortiz", value: -1, updatedAt: "2026-03-15T09:25:00.000Z" },
  { id: "pulse-12", taskId: "maintainer-sustainability-forecast", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T09:28:00.000Z" },
  { id: "pulse-13", taskId: "maintainer-sustainability-forecast", profileId: "jordan-miles", value: -1, updatedAt: "2026-03-15T09:30:00.000Z" },
  { id: "pulse-14", taskId: "local-air-quality-alert-compiler", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-03-15T09:33:00.000Z" },
  { id: "pulse-15", taskId: "local-air-quality-alert-compiler", profileId: "priya-singh", value: 1, updatedAt: "2026-03-15T09:35:00.000Z" },
  { id: "pulse-16", taskId: "local-air-quality-alert-compiler", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T09:37:00.000Z" },
  { id: "pulse-17", taskId: "benefit-appeals-document-navigator", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T09:40:00.000Z" },
  { id: "pulse-18", taskId: "benefit-appeals-document-navigator", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-03-15T09:42:00.000Z" },
  { id: "pulse-19", taskId: "municipal-budget-red-flag-monitor", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T09:44:00.000Z" },
  { id: "pulse-20", taskId: "rare-disease-literature-mapper", profileId: "noor-haddad", value: 1, updatedAt: "2026-03-15T09:46:00.000Z" },
  { id: "pulse-21", taskId: "rare-disease-literature-mapper", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T09:49:00.000Z" },
  { id: "pulse-22", taskId: "open-materials-discovery-notebook", profileId: "noor-haddad", value: 1, updatedAt: "2026-03-15T09:51:00.000Z" },
  { id: "pulse-23", taskId: "reproducible-dataset-pipeline", profileId: "noor-haddad", value: 1, updatedAt: "2026-03-15T09:53:00.000Z" },
  { id: "pulse-24", taskId: "patch-review-triage-copilot", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-03-15T09:56:00.000Z" },
  { id: "pulse-25", taskId: "civic-procurement-spec-checker", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T09:59:00.000Z" },
  { id: "pulse-26", taskId: "translation-workbench-for-disaster-ops", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T10:02:00.000Z" },
  { id: "pulse-27", taskId: "public-domain-storyworld-builder", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T10:06:00.000Z" },
  { id: "pulse-28", taskId: "public-domain-storyworld-builder", profileId: "noor-haddad", value: -1, updatedAt: "2026-03-15T10:08:00.000Z" },
  { id: "pulse-29", taskId: "autonomous-exploit-kit-tuner", profileId: "maya-chen", value: -1, updatedAt: "2026-03-15T10:12:00.000Z" },
  { id: "pulse-30", taskId: "autonomous-exploit-kit-tuner", profileId: "aiko-tanaka", value: -1, updatedAt: "2026-03-15T10:15:00.000Z" },
];

export const seedCheckpointGates: CheckpointGateRecord[] = [
  { checkpointId: "checkpoint-1", approvalScore: 29, requiredApprovals: 24, releaseStatus: "approved" },
  { checkpointId: "checkpoint-2", approvalScore: 18, requiredApprovals: 24, releaseStatus: "pending" },
  { checkpointId: "checkpoint-3", approvalScore: 14, requiredApprovals: 16, releaseStatus: "pending" },
  { checkpointId: "checkpoint-4", approvalScore: 0, requiredApprovals: 16, releaseStatus: "held" },
  { checkpointId: "checkpoint-5", approvalScore: 19, requiredApprovals: 20, releaseStatus: "pending" },
  { checkpointId: "checkpoint-6", approvalScore: 0, requiredApprovals: 22, releaseStatus: "pending" },
  { checkpointId: "checkpoint-7", approvalScore: 11, requiredApprovals: 12, releaseStatus: "pending" },
  { checkpointId: "checkpoint-8", approvalScore: 0, requiredApprovals: 14, releaseStatus: "pending" },
  { checkpointId: "checkpoint-9", approvalScore: 0, requiredApprovals: 20, releaseStatus: "pending" },
  { checkpointId: "checkpoint-10", approvalScore: 18, requiredApprovals: 12, releaseStatus: "approved" },
];

export const seedComments: CommentRecord[] = [
  { id: "comment-1", taskId: "critical-oss-regression-radar", profileId: "elena-petrov", parentId: null, body: "The strongest part of this proposal is that the output is not just another dashboard. If the run keeps publishing replayable failing cases and rollback-ready diffs, maintainers can actually act on it during bad release weeks.", stakeCredits: 3, createdAt: "2026-03-15T11:00:00.000Z" },
  { id: "comment-2", taskId: "critical-oss-regression-radar", profileId: "maya-chen", parentId: "comment-1", body: "Agreed. I also want the checkpoint packet to expose false positives explicitly so the system cannot quietly optimize for volume over trust.", stakeCredits: 2, createdAt: "2026-03-15T11:08:00.000Z" },
  { id: "comment-3", taskId: "multi-model-agent-eval-harness", profileId: "aiko-tanaka", parentId: null, body: "This should keep a public manifest for tools, budgets, and failure classes. Otherwise people will argue about benchmark vibes instead of inspecting the actual run conditions.", stakeCredits: 3, createdAt: "2026-03-15T11:14:00.000Z" },
  { id: "comment-4", taskId: "multi-model-agent-eval-harness", profileId: "noor-haddad", parentId: "comment-3", body: "Please include a science-oriented lane with contradiction preservation. Most eval suites still flatten uncertainty in a way that makes them useless for real literature work.", stakeCredits: 2, createdAt: "2026-03-15T11:22:00.000Z" },
  { id: "comment-5", taskId: "benefit-appeals-document-navigator", profileId: "jordan-miles", parentId: null, body: "The product should never pretend to replace advocates. The realistic win is faster source-grounded first drafts, better issue spotting, and fewer people missing deadlines because a packet was incomprehensible.", stakeCredits: 3, createdAt: "2026-03-15T11:28:00.000Z" },
  { id: "comment-6", taskId: "benefit-appeals-document-navigator", profileId: "rafael-ortiz", parentId: "comment-5", body: "Yes. If the interface foregrounds citations and advocate editability, this becomes public-interest infrastructure instead of a legal-advice trap.", stakeCredits: 2, createdAt: "2026-03-15T11:35:00.000Z" },
  { id: "comment-7", taskId: "rare-disease-literature-mapper", profileId: "noor-haddad", parentId: null, body: "What matters here is continuity. Small labs can sometimes get a one-off literature review, but they rarely get a living map that preserves contradictions and keeps updating as new evidence lands.", stakeCredits: 3, createdAt: "2026-03-15T11:44:00.000Z" },
  { id: "comment-8", taskId: "rare-disease-literature-mapper", profileId: "priya-singh", parentId: "comment-7", body: "I would also like the checkpoint gates to require explicit uncertainty labels before each new tranche. That is the only way to keep the atlas useful for real-world teams.", stakeCredits: 2, createdAt: "2026-03-15T11:49:00.000Z" },
  { id: "comment-9", taskId: "local-air-quality-alert-compiler", profileId: "rafael-ortiz", parentId: null, body: "This is the kind of boring, realistic public-interest work that can justify continuous compute. The value is in relentless source freshness and accessibility, not just one elegant summary.", stakeCredits: 3, createdAt: "2026-03-15T11:55:00.000Z" },
  { id: "comment-10", taskId: "local-air-quality-alert-compiler", profileId: "jordan-miles", parentId: "comment-9", body: "If the public output keeps plain-language action templates and links every recommendation to a source, I can see local newsrooms and schools using it immediately.", stakeCredits: 2, createdAt: "2026-03-15T12:01:00.000Z" },
  { id: "comment-11", taskId: "autonomous-exploit-kit-tuner", profileId: "aiko-tanaka", parentId: null, body: "Keeping blocked work visible is important. The denial itself is part of the product's legitimacy because it shows the safety boundary instead of quietly pretending harmful demand does not exist.", stakeCredits: 1, createdAt: "2026-03-15T12:08:00.000Z" },
  { id: "comment-12", taskId: "public-domain-storyworld-builder", profileId: "maya-chen", parentId: null, body: "Creative work belongs here when provenance is strict and the outputs stay open. A lot of archival labor is still too expensive for small teams to sustain continuously.", stakeCredits: 1, createdAt: "2026-03-15T12:16:00.000Z" },
];

export const seedCommentVotes: CommentVoteRecord[] = [
  { id: "comment-vote-1", commentId: "comment-1", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T12:30:00.000Z" },
  { id: "comment-vote-2", commentId: "comment-1", profileId: "aiko-tanaka", value: 1, updatedAt: "2026-03-15T12:31:00.000Z" },
  { id: "comment-vote-3", commentId: "comment-2", profileId: "elena-petrov", value: 1, updatedAt: "2026-03-15T12:33:00.000Z" },
  { id: "comment-vote-4", commentId: "comment-3", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T12:34:00.000Z" },
  { id: "comment-vote-5", commentId: "comment-3", profileId: "elena-petrov", value: 1, updatedAt: "2026-03-15T12:35:00.000Z" },
  { id: "comment-vote-6", commentId: "comment-4", profileId: "priya-singh", value: 1, updatedAt: "2026-03-15T12:37:00.000Z" },
  { id: "comment-vote-7", commentId: "comment-5", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-03-15T12:39:00.000Z" },
  { id: "comment-vote-8", commentId: "comment-5", profileId: "priya-singh", value: 1, updatedAt: "2026-03-15T12:40:00.000Z" },
  { id: "comment-vote-9", commentId: "comment-6", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T12:42:00.000Z" },
  { id: "comment-vote-10", commentId: "comment-7", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T12:44:00.000Z" },
  { id: "comment-vote-11", commentId: "comment-7", profileId: "priya-singh", value: 1, updatedAt: "2026-03-15T12:45:00.000Z" },
  { id: "comment-vote-12", commentId: "comment-8", profileId: "noor-haddad", value: 1, updatedAt: "2026-03-15T12:46:00.000Z" },
  { id: "comment-vote-13", commentId: "comment-9", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T12:48:00.000Z" },
  { id: "comment-vote-14", commentId: "comment-9", profileId: "priya-singh", value: 1, updatedAt: "2026-03-15T12:49:00.000Z" },
  { id: "comment-vote-15", commentId: "comment-10", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-03-15T12:51:00.000Z" },
  { id: "comment-vote-16", commentId: "comment-11", profileId: "maya-chen", value: 1, updatedAt: "2026-03-15T12:53:00.000Z" },
  { id: "comment-vote-17", commentId: "comment-11", profileId: "elena-petrov", value: 1, updatedAt: "2026-03-15T12:54:00.000Z" },
  { id: "comment-vote-18", commentId: "comment-12", profileId: "jordan-miles", value: 1, updatedAt: "2026-03-15T12:56:00.000Z" },
  { id: "comment-vote-19", commentId: "comment-12", profileId: "noor-haddad", value: -1, updatedAt: "2026-03-15T12:57:00.000Z" },
];

export const seedRevenueStreams: RevenueStreamRecord[] = [
  { id: "revenue-1", slug: "enterprise-packaging", name: "Enterprise packaging", engine: "enterprise", description: "Managed APIs, hosted agents, and SLA-backed workflow products built from open KenMatch outputs.", pricingModel: "Annual subscriptions plus implementation retainers", status: "live", monthlyRevenueUsd: 62000, grossMargin: 0.81, treasurySharePercent: 80, founderSharePercent: 20 },
  { id: "revenue-2", slug: "preference-licensing", name: "Preference and trajectory licensing", engine: "data-licensing", description: "Anonymized, privacy-screened curation and checkpoint data licensed for frontier training and evaluation.", pricingModel: "Quarterly licensing agreements", status: "pilot", monthlyRevenueUsd: 28000, grossMargin: 0.78, treasurySharePercent: 80, founderSharePercent: 20 },
  { id: "revenue-3", slug: "asymmetric-compute-arbitrage", name: "Asymmetric compute arbitrage", engine: "compute-arbitrage", description: "Enterprise workloads sold at standard rates and fulfilled during cheaper off-peak windows on neutral compute markets.", pricingModel: "Usage-based orchestration margin", status: "live", monthlyRevenueUsd: 19000, grossMargin: 0.74, treasurySharePercent: 80, founderSharePercent: 20 },
  { id: "revenue-4", slug: "civic-sponsorships", name: "Civic sponsorships", engine: "sponsorship", description: "Mission-aligned underwriting for specific public-interest compute lanes and open deliverables.", pricingModel: "Restricted sponsorship pools", status: "planned", monthlyRevenueUsd: 12000, grossMargin: 0.55, treasurySharePercent: 90, founderSharePercent: 10 },
];

export const seedTreasuryEntries: TreasuryEntryRecord[] = [
  { id: "treasury-1", streamId: "revenue-1", title: "Enterprise packaging routing", description: "March enterprise product revenue routed into the public compute treasury under the 80/20 rule.", bucket: "compute-treasury", direction: "inflow", amountUsd: 49600, createdAt: "2026-03-01T09:00:00.000Z" },
  { id: "treasury-2", streamId: "revenue-2", title: "Preference licensing routing", description: "Pilot licensing proceeds from curated checkpoint and preference data.", bucket: "compute-treasury", direction: "inflow", amountUsd: 22400, createdAt: "2026-03-03T09:00:00.000Z" },
  { id: "treasury-3", streamId: "revenue-3", title: "Compute arbitrage surplus", description: "Margin captured from off-peak neutral compute routing for enterprise workloads.", bucket: "compute-treasury", direction: "inflow", amountUsd: 15200, createdAt: "2026-03-05T09:00:00.000Z" },
  { id: "treasury-4", streamId: "revenue-4", title: "Restricted civic sponsorship pool", description: "Underwriting reserved for public-interest alerting and benefits-support lanes.", bucket: "compute-treasury", direction: "inflow", amountUsd: 10800, createdAt: "2026-03-06T09:00:00.000Z" },
  { id: "treasury-5", streamId: null, title: "Month-tier compute allocation", description: "Capital released to continuous month-scale runs after checkpoint approval.", bucket: "compute-treasury", direction: "outflow", amountUsd: 54000, createdAt: "2026-03-08T09:00:00.000Z" },
  { id: "treasury-6", streamId: null, title: "Week-tier compute allocation", description: "Funded active and scheduled week-scale runs across public-interest and infrastructure lanes.", bucket: "compute-treasury", direction: "outflow", amountUsd: 16000, createdAt: "2026-03-09T09:00:00.000Z" },
  { id: "treasury-7", streamId: null, title: "Safety and audit reserve", description: "External review, checkpoint moderation, and incident-response reserve.", bucket: "compute-treasury", direction: "outflow", amountUsd: 7000, createdAt: "2026-03-10T09:00:00.000Z" },
  { id: "treasury-8", streamId: null, title: "Founder sustenance transfer", description: "Founder operations routed to the holding company under the public 80/20 reporting rule.", bucket: "founder-ops", direction: "inflow", amountUsd: 15500, createdAt: "2026-03-11T09:00:00.000Z" },
];
