import type {
  CheckpointGateRecord,
  CommentRecord,
  CommentVoteRecord,
  ProfileAttestationRecord,
  RevenueStreamRecord,
  RunUpdateRecord,
  SponsorshipCommitmentRecord,
  TaskFinanceRecord,
  TaskPulseVoteRecord,
  TaskTimingRecord,
  TreasuryEntryRecord,
} from "@/lib/types";

const frontierModelLineup = [
  "OpenAI o3-deep-research",
  "OpenAI GPT-5.2",
  "Claude Opus 4.1",
  "Gemini 3 Pro Preview",
  "xAI Grok 4.1 Fast",
  "sandbox evaluator ensemble",
];

export const seedProfileAttestations: ProfileAttestationRecord[] = [
  { profileId: "maya-chen", provider: "Maintainer history + manual review", status: "verified", sybilRisk: "low", reviewedAt: "2026-04-24T10:00:00.000Z", signals: ["Signed release history", "Independent code references"], note: "The pseudonymous maintainer identity has enough public track record for full participation without exposing unrelated personal details." },
  { profileId: "noor-haddad", provider: "Publication graph + institutional review", status: "verified", sybilRisk: "low", reviewedAt: "2026-04-24T16:30:00.000Z", signals: ["Linked research outputs", "Conference and foundation references"], note: "Research contribution history is established and mapped to the profile claim." },
  { profileId: "rafael-ortiz", provider: "Public-interest portfolio + domain verification", status: "verified", sybilRisk: "low", reviewedAt: "2026-04-23T13:20:00.000Z", signals: ["Civic-work archive", "Organization email review"], note: "Public-interest work and identity signals are consistent enough for full voice capacity." },
  { profileId: "elena-petrov", provider: "Security maintainer review", status: "verified", sybilRisk: "low", reviewedAt: "2026-04-23T14:10:00.000Z", signals: ["Signed advisories", "Maintainer attestations"], note: "Defensive-security expertise was manually reviewed before higher-weight safety participation." },
  { profileId: "aiko-tanaka", provider: "Portfolio review + repeat client references", status: "verified", sybilRisk: "medium", reviewedAt: "2026-04-25T09:45:00.000Z", signals: ["Public portfolio", "Reference check"], note: "Creative and archive work is credible, with a moderate cap because some references are pseudonymous." },
  { profileId: "jordan-miles", provider: "Research administration review", status: "review", sybilRisk: "medium", reviewedAt: "2026-04-25T11:15:00.000Z", signals: ["Program references", "Long-form writing samples"], note: "Participation is active and credible, with one remaining institutional verification step pending." },
  { profileId: "priya-singh", provider: "Clinic operations references + manual review", status: "verified", sybilRisk: "low", reviewedAt: "2026-04-25T15:00:00.000Z", signals: ["Partner references", "Program delivery history"], note: "Operational identity and track record support full participation." },
];

export const seedTaskFinance: TaskFinanceRecord[] = [
  { taskId: "home-energy-upgrade-companion", qualityBondCredits: 4, sponsorPoolUsd: 13500, checkpointApprovalTarget: 16, enterprisePackaging: "Reproducibility scout for small labs, methods sections, and protocol repositories that need source-linked extraction before wet-lab time is spent.", dataValueNote: "Reviewer corrections on reagents, units, ambiguity, and missing controls become high-value evaluation traces for scientific workflow agents.", sandboxCapitalUsd: 2100, sandboxApiSpendUsd: 480, sandboxPilotUsers: 24, modelLineup: frontierModelLineup, simulationSummary: "A simulated weeks-lane run extracts methods from papers, flags missing protocol details, and preserves every reviewer correction as an auditable trace.", sampleOutcome: "The demo surfaced 43 ambiguous protocol steps across 18 papers and produced reviewer-ready checklists for 6 reproduction attempts.", sponsorAppeal: "Strong fit for disease foundations, core facilities, preprint communities, and reproducibility groups because the output reduces wasted bench cycles without pretending to run experiments autonomously." },
  { taskId: "repair-manual-finder", qualityBondCredits: 2, sponsorPoolUsd: 5200, checkpointApprovalTarget: 8, enterprisePackaging: "Maintainer-facing regression reproducer that turns user reports and release notes into minimal failing cases and rollback packets.", dataValueNote: "Accepted reproductions, false-positive dismissals, and patch links form practical software-engineering evaluation data.", sandboxCapitalUsd: 740, sandboxApiSpendUsd: 156, sandboxPilotUsers: 34, modelLineup: frontierModelLineup, simulationSummary: "The sandbox replayed package updates, synthesized failing tests, and produced concise maintainer packets instead of generic issue summaries.", sampleOutcome: "The simulated run reproduced 9 of 14 reported regressions and closed early after the public release threshold was reached.", sponsorAppeal: "A believable sponsor fit for foundations, registries, and developer-tool companies because a small days-lane grant produces visible maintenance leverage." },
  { taskId: "benefit-appeal-packet-helper", qualityBondCredits: 3, sponsorPoolUsd: 11800, checkpointApprovalTarget: 18, enterprisePackaging: "Research-administration copilot for grant calls, IRB requirements, data-management plans, and collaborator deadline tracking.", dataValueNote: "Human edits to requirement maps and deadline plans create strong supervision for rule-grounded planning agents.", sandboxCapitalUsd: 1650, sandboxApiSpendUsd: 330, sandboxPilotUsers: 31, modelLineup: frontierModelLineup, simulationSummary: "The demo maps call requirements into source-linked checklists, highlights missing attachments, and keeps human administrators in the approval loop.", sampleOutcome: "A simulated pilot cut first-pass eligibility review from 64 minutes to 19 minutes while preserving every citation and uncertainty note.", sponsorAppeal: "Useful to universities, foundations, and small research teams because it converts administrative bottlenecks into auditable work plans instead of opaque automation." },
  { taskId: "small-town-procurement-checker", qualityBondCredits: 2, sponsorPoolUsd: 4200, checkpointApprovalTarget: 8, enterprisePackaging: "Public-records review layer for city contracts, procurement drafts, board packets, and grant spending summaries.", dataValueNote: "Corrections on red flags, false alarms, and cited source spans improve public-sector document review benchmarks.", sandboxCapitalUsd: 680, sandboxApiSpendUsd: 140, sandboxPilotUsers: 18, modelLineup: frontierModelLineup, simulationSummary: "The sandbox compares agendas, contract language, change orders, and prior bids to surface contradictions before public meetings.", sampleOutcome: "The demo flagged 22 review-worthy issues across 11 mock packets and correctly dismissed 17 distracting non-issues.", sponsorAppeal: "A practical civic-tech sponsorship because the value is readable to residents and staff without granting sponsors influence over ranking." },
  { taskId: "local-air-quality-briefing", qualityBondCredits: 4, sponsorPoolUsd: 15500, checkpointApprovalTarget: 22, enterprisePackaging: "Source-linked smoke, heat, and school-operations briefing layer for clinics, districts, parent groups, and local newsrooms.", dataValueNote: "Source conflict resolutions, regional corrections, and latency audits improve real-time public-information agents.", sandboxCapitalUsd: 2850, sandboxApiSpendUsd: 560, sandboxPilotUsers: 880, modelLineup: frontierModelLineup, simulationSummary: "The simulated month-lane run combines public sensor feeds, district notices, and clinic guidance into morning briefs with explicit source freshness.", sampleOutcome: "A demo cohort of 880 subscribers received neighborhood-specific briefs with median source-to-summary latency under 12 minutes.", sponsorAppeal: "High-engagement fit for air districts, pediatric networks, climate-health funds, and regional journalism teams." },
  { taskId: "open-source-security-regression-watch", qualityBondCredits: 5, sponsorPoolUsd: 18200, checkpointApprovalTarget: 24, enterprisePackaging: "Defensive release-intelligence feed for maintainers, registries, and platform security teams that need reproducible incident packets.", dataValueNote: "Replay adjudications, embargo handling, and maintainer corrections build unusually useful defensive evaluation data.", sandboxCapitalUsd: 3350, sandboxApiSpendUsd: 650, sandboxPilotUsers: 27, modelLineup: frontierModelLineup, simulationSummary: "The sandbox replays dependency changes, builds reproducible regression packets, and withholds sensitive detail until human embargo approval.", sampleOutcome: "The demo produced 4 clean replay bundles, held 1 advisory behind embargo review, and rejected 12 noisy signals.", sponsorAppeal: "Realistic for foundations, registries, and security programs because it funds public defensive capacity rather than private alert hoarding." },
  { taskId: "rare-disease-evidence-atlas", qualityBondCredits: 4, sponsorPoolUsd: 16800, checkpointApprovalTarget: 24, enterprisePackaging: "Living evidence atlas for patient foundations, small labs, and clinician-scientist teams that need continuity instead of one-off literature reviews.", dataValueNote: "Expert contradiction handling, revision histories, and uncertainty edits create valuable scientific synthesis traces.", sandboxCapitalUsd: 3600, sandboxApiSpendUsd: 710, sandboxPilotUsers: 42, modelLineup: frontierModelLineup, simulationSummary: "The simulated month-lane run keeps mechanisms, biomarkers, interventions, and negative findings visible over time instead of flattening the literature into one answer.", sampleOutcome: "The demo merged 128 papers into a contradiction-preserving map with 21 specialist correction notes and 14 open questions.", sponsorAppeal: "Compelling for disease foundations because backing buys living synthesis capacity that small communities rarely sustain." },
  { taskId: "clinic-follow-up-question-drafter", qualityBondCredits: 2, sponsorPoolUsd: 3500, checkpointApprovalTarget: 8, enterprisePackaging: "Narrow clinical-note triage support with mandatory clinician sign-off and conservative refusal boundaries.", dataValueNote: "Accepted, edited, and rejected prompts sharpen safe medical drafting workflows without replacing clinical judgment.", sandboxCapitalUsd: 520, sandboxApiSpendUsd: 110, sandboxPilotUsers: 35, modelLineup: frontierModelLineup, simulationSummary: "The sandbox turns specialist notes into concise follow-up question sets that clinicians can keep, edit, or discard.", sampleOutcome: "Clinicians in the demo kept at least one drafted question in 72 percent of reviewed cases, then stopped expansion at the compute limit.", sponsorAppeal: "Easy to explain to clinic backers because the scope is narrow, the guardrails are visible, and partial value is still useful." },
  { taskId: "museum-oral-history-indexer", qualityBondCredits: 2, sponsorPoolUsd: 7600, checkpointApprovalTarget: 12, enterprisePackaging: "Archive indexing and exhibit-prep workflow for museums, libraries, schools, and local history programs with limited staff.", dataValueNote: "Metadata corrections, rights notes, OCR fixes, and topic labels improve cultural-archive tooling.", sandboxCapitalUsd: 1120, sandboxApiSpendUsd: 230, sandboxPilotUsers: 13, modelLineup: frontierModelLineup, simulationSummary: "The simulated run converts long interviews and scanned materials into searchable clips, rights-aware summaries, and exhibit-ready quote cards.", sampleOutcome: "A 31-hour oral-history batch became 242 searchable segments, 46 cleaned quote cards, and a rights-review queue.", sponsorAppeal: "Good fit for libraries, schools, arts councils, and local donors because the output is immediately legible and culturally valuable." },
  { taskId: "public-domain-performance-studio", qualityBondCredits: 1, sponsorPoolUsd: 3400, checkpointApprovalTarget: 8, enterprisePackaging: "Rights-safe creative packet builder for schools, libraries, youth programs, and community theater groups.", dataValueNote: "Rights validation, rehearsal edits, and public-domain source maps improve creative planning tools.", sandboxCapitalUsd: 410, sandboxApiSpendUsd: 90, sandboxPilotUsers: 22, modelLineup: frontierModelLineup, simulationSummary: "The days-lane sandbox assembles rehearsal packets, scene breakdowns, prop notes, and accessible program copy from clearly licensed material.", sampleOutcome: "Two simulated theater groups produced a full starter packet in under 20 minutes and caught 6 rights issues before rehearsal.", sponsorAppeal: "Appealing to schools and arts councils because a small grant produces a visible creative public demo rather than abstract infrastructure." },
  { taskId: "school-lunch-menu-translator", qualityBondCredits: 1, sponsorPoolUsd: 4200, checkpointApprovalTarget: 8, enterprisePackaging: "Reviewed translation and allergen-clarity workflow for school districts and parent groups.", dataValueNote: "Native-speaker edits and allergen corrections improve multilingual document agents in a bounded, useful setting.", sandboxCapitalUsd: 520, sandboxApiSpendUsd: 100, sandboxPilotUsers: 68, modelLineup: frontierModelLineup, simulationSummary: "The sandbox translates menu PDFs, preserves allergen caveats, and routes uncertain phrases to native-speaker review.", sampleOutcome: "The demo produced 36 reviewed menu cards across three languages and flagged 11 allergen phrases for human confirmation.", sponsorAppeal: "A clear days-lane sponsorship because families can understand the value immediately and every translation remains review-gated." },
  { taskId: "neighborhood-pothole-tracker", qualityBondCredits: 1, sponsorPoolUsd: 3000, checkpointApprovalTarget: 8, enterprisePackaging: "Permit and queue monitor for residents, journalists, and small civic groups tracking public works backlogs.", dataValueNote: "Corrections on document references, project status, and agency ownership create useful public-records evaluation data.", sandboxCapitalUsd: 390, sandboxApiSpendUsd: 82, sandboxPilotUsers: 19, modelLineup: frontierModelLineup, simulationSummary: "The demo links permit records, council agendas, and public works updates into a plain-language status board.", sampleOutcome: "The simulated run reconciled 73 queue items and identified 8 records needing agency clarification.", sponsorAppeal: "A local-news or civic-fund fit because the deliverable makes public records easier to inspect without making policy decisions." },
  { taskId: "freelancer-invoice-checker", qualityBondCredits: 1, sponsorPoolUsd: 2800, checkpointApprovalTarget: 8, enterprisePackaging: "Research dataset license and consent scanner for small labs, open-source maintainers, and student teams.", dataValueNote: "Human-reviewed license boundaries and false-positive corrections improve compliance-oriented data tooling.", sandboxCapitalUsd: 360, sandboxApiSpendUsd: 76, sandboxPilotUsers: 17, modelLineup: frontierModelLineup, simulationSummary: "The days-lane sandbox scans dataset cards, repository licenses, consent notes, and redistribution language before a project publishes.", sampleOutcome: "The demo flagged 12 license risks, cleared 28 safe records, and produced a reviewer queue for 5 ambiguous datasets.", sponsorAppeal: "Useful for universities and open-data groups because the value is concrete, limited, and defensible." },
  { taskId: "autonomous-phishing-lure-optimizer", qualityBondCredits: 5, sponsorPoolUsd: 0, checkpointApprovalTarget: 0, enterprisePackaging: "No commercial path because the Ken is blocked as prohibited offensive work.", dataValueNote: "No data collection or commercialization is allowed for blocked abuse-oriented Kens.", sandboxCapitalUsd: 0, sandboxApiSpendUsd: 0, sandboxPilotUsers: 0, modelLineup: [], simulationSummary: "No sandbox run is allowed because the proposed outcome increases real-world abuse capacity.", sampleOutcome: "No public demo output is generated for blocked offensive Kens.", sponsorAppeal: "Sponsors cannot fund or revive blocked offensive work." },
];

export const seedTaskPulseVotes: TaskPulseVoteRecord[] = [
  { id: "pulse-1", taskId: "home-energy-upgrade-companion", profileId: "noor-haddad", value: 1, updatedAt: "2026-04-25T10:00:00.000Z" },
  { id: "pulse-2", taskId: "home-energy-upgrade-companion", profileId: "maya-chen", value: 1, updatedAt: "2026-04-25T10:02:00.000Z" },
  { id: "pulse-3", taskId: "repair-manual-finder", profileId: "maya-chen", value: 1, updatedAt: "2026-04-25T10:05:00.000Z" },
  { id: "pulse-4", taskId: "benefit-appeal-packet-helper", profileId: "jordan-miles", value: 1, updatedAt: "2026-04-25T10:08:00.000Z" },
  { id: "pulse-5", taskId: "benefit-appeal-packet-helper", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-04-25T10:10:00.000Z" },
  { id: "pulse-6", taskId: "small-town-procurement-checker", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-04-25T10:12:00.000Z" },
  { id: "pulse-7", taskId: "local-air-quality-briefing", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-04-25T10:16:00.000Z" },
  { id: "pulse-8", taskId: "local-air-quality-briefing", profileId: "priya-singh", value: 1, updatedAt: "2026-04-25T10:18:00.000Z" },
  { id: "pulse-9", taskId: "local-air-quality-briefing", profileId: "jordan-miles", value: 1, updatedAt: "2026-04-25T10:21:00.000Z" },
  { id: "pulse-10", taskId: "open-source-security-regression-watch", profileId: "elena-petrov", value: 1, updatedAt: "2026-04-25T10:24:00.000Z" },
  { id: "pulse-11", taskId: "open-source-security-regression-watch", profileId: "maya-chen", value: 1, updatedAt: "2026-04-25T10:26:00.000Z" },
  { id: "pulse-12", taskId: "rare-disease-evidence-atlas", profileId: "noor-haddad", value: 1, updatedAt: "2026-04-25T10:30:00.000Z" },
  { id: "pulse-13", taskId: "rare-disease-evidence-atlas", profileId: "priya-singh", value: 1, updatedAt: "2026-04-25T10:32:00.000Z" },
  { id: "pulse-14", taskId: "clinic-follow-up-question-drafter", profileId: "priya-singh", value: 1, updatedAt: "2026-04-25T10:35:00.000Z" },
  { id: "pulse-15", taskId: "museum-oral-history-indexer", profileId: "aiko-tanaka", value: 1, updatedAt: "2026-04-25T10:39:00.000Z" },
  { id: "pulse-16", taskId: "public-domain-performance-studio", profileId: "aiko-tanaka", value: 1, updatedAt: "2026-04-25T10:42:00.000Z" },
  { id: "pulse-17", taskId: "school-lunch-menu-translator", profileId: "priya-singh", value: 1, updatedAt: "2026-04-25T10:43:00.000Z" },
  { id: "pulse-18", taskId: "freelancer-invoice-checker", profileId: "maya-chen", value: 1, updatedAt: "2026-04-25T10:44:00.000Z" },
  { id: "pulse-19", taskId: "autonomous-phishing-lure-optimizer", profileId: "maya-chen", value: -1, updatedAt: "2026-04-25T10:47:00.000Z" },
  { id: "pulse-20", taskId: "autonomous-phishing-lure-optimizer", profileId: "elena-petrov", value: -1, updatedAt: "2026-04-25T10:49:00.000Z" },
];

export const seedTaskTimings: TaskTimingRecord[] = [
  { taskId: "home-energy-upgrade-companion", launchAt: "2026-04-18T09:00:00.000Z", startedAt: "2026-04-18T09:00:00.000Z", expectedMaxEndAt: "2026-05-02T09:00:00.000Z", computeHoursUsed: 178, completionMode: "running", completionSummary: "Protocol extraction is running with ambiguity labels and reviewer corrections visible before wider source expansion.", updatedAt: "2026-04-25T18:30:00.000Z" },
  { taskId: "repair-manual-finder", launchAt: "2026-04-21T08:00:00.000Z", startedAt: "2026-04-21T08:00:00.000Z", expectedMaxEndAt: "2026-04-24T08:00:00.000Z", computeHoursUsed: 49, completionMode: "completed-early", completionSummary: "The reproducer shipped early after failing-test quality cleared the release threshold before the full compute window was needed.", updatedAt: "2026-04-23T09:10:00.000Z" },
  { taskId: "benefit-appeal-packet-helper", launchAt: "2026-04-27T10:00:00.000Z", startedAt: null, expectedMaxEndAt: "2026-05-04T10:00:00.000Z", computeHoursUsed: 0, completionMode: "planned", completionSummary: "Waiting on requirement freshness and research-admin pilot sign-off.", updatedAt: "2026-04-25T16:20:00.000Z" },
  { taskId: "small-town-procurement-checker", launchAt: "2026-04-27T09:00:00.000Z", startedAt: null, expectedMaxEndAt: "2026-04-29T09:00:00.000Z", computeHoursUsed: 0, completionMode: "planned", completionSummary: "Queued behind public ranking and final source-boundary review.", updatedAt: "2026-04-25T15:40:00.000Z" },
  { taskId: "local-air-quality-briefing", launchAt: "2026-04-10T06:00:00.000Z", startedAt: "2026-04-10T06:00:00.000Z", expectedMaxEndAt: "2026-05-10T06:00:00.000Z", computeHoursUsed: 390, completionMode: "running", completionSummary: "Daily public briefings are live and expanding source freshness checks across districts.", updatedAt: "2026-04-25T17:45:00.000Z" },
  { taskId: "open-source-security-regression-watch", launchAt: "2026-04-11T12:00:00.000Z", startedAt: "2026-04-11T12:00:00.000Z", expectedMaxEndAt: "2026-05-11T12:00:00.000Z", computeHoursUsed: 372, completionMode: "running", completionSummary: "Replay bundles are flowing, with one embargoed advisory held behind human review.", updatedAt: "2026-04-25T13:15:00.000Z" },
  { taskId: "rare-disease-evidence-atlas", launchAt: "2026-04-12T09:00:00.000Z", startedAt: "2026-04-12T09:00:00.000Z", expectedMaxEndAt: "2026-05-12T09:00:00.000Z", computeHoursUsed: 336, completionMode: "running", completionSummary: "The atlas is live with specialist corrections and contradiction labels preserved.", updatedAt: "2026-04-25T14:20:00.000Z" },
  { taskId: "clinic-follow-up-question-drafter", launchAt: "2026-04-20T08:30:00.000Z", startedAt: "2026-04-20T08:30:00.000Z", expectedMaxEndAt: "2026-04-23T08:30:00.000Z", computeHoursUsed: 72, completionMode: "completed-at-limit", completionSummary: "The pilot shipped narrow value, then stopped at the compute limit pending more conservative clinical controls.", updatedAt: "2026-04-23T18:00:00.000Z" },
  { taskId: "museum-oral-history-indexer", launchAt: "2026-04-28T11:00:00.000Z", startedAt: null, expectedMaxEndAt: "2026-05-04T11:00:00.000Z", computeHoursUsed: 0, completionMode: "planned", completionSummary: "Waiting on archive rights review before ingestion begins.", updatedAt: "2026-04-25T10:50:00.000Z" },
  { taskId: "public-domain-performance-studio", launchAt: "2026-04-26T09:30:00.000Z", startedAt: null, expectedMaxEndAt: "2026-04-28T15:30:00.000Z", computeHoursUsed: 0, completionMode: "planned", completionSummary: "Gathering public signal and community-theater pilot partners.", updatedAt: "2026-04-25T09:10:00.000Z" },
  { taskId: "school-lunch-menu-translator", launchAt: "2026-04-28T12:00:00.000Z", startedAt: null, expectedMaxEndAt: "2026-04-30T12:00:00.000Z", computeHoursUsed: 0, completionMode: "planned", completionSummary: "Waiting on district menu samples and native-speaker review volunteers.", updatedAt: "2026-04-25T10:00:00.000Z" },
  { taskId: "neighborhood-pothole-tracker", launchAt: "2026-04-29T08:00:00.000Z", startedAt: null, expectedMaxEndAt: "2026-05-01T08:00:00.000Z", computeHoursUsed: 0, completionMode: "planned", completionSummary: "Collecting public-record samples before a days-lane monitor test.", updatedAt: "2026-04-25T10:05:00.000Z" },
  { taskId: "freelancer-invoice-checker", launchAt: "2026-04-29T10:00:00.000Z", startedAt: null, expectedMaxEndAt: "2026-04-30T22:00:00.000Z", computeHoursUsed: 0, completionMode: "planned", completionSummary: "Collecting dataset-card and repository-license examples before a narrow scan.", updatedAt: "2026-04-25T10:10:00.000Z" },
  { taskId: "autonomous-phishing-lure-optimizer", launchAt: null, startedAt: null, expectedMaxEndAt: null, computeHoursUsed: 0, completionMode: "blocked", completionSummary: "Blocked before launch because the Ken improves offensive abuse capability.", updatedAt: "2026-04-25T11:00:00.000Z" },
];

export const seedRunUpdates: RunUpdateRecord[] = [
  { id: "update-1", taskId: "home-energy-upgrade-companion", label: "First protocol extraction pass delivered", status: "on-track", summary: "The run extracted source-linked steps, units, reagents, and ambiguity notes from the first paper set.", artifact: "Protocol extraction packet", evidenceNote: "Every extracted step links back to a source passage and reviewer comment.", createdAt: "2026-04-22T17:00:00.000Z" },
  { id: "update-2", taskId: "home-energy-upgrade-companion", label: "Reviewer ambiguity sweep expanded", status: "on-track", summary: "Domain reviewers added missing-control notes and rejected inferred bench steps without explicit support.", artifact: "Ambiguity review diff", evidenceNote: "Accepted and rejected corrections are preserved for audit.", createdAt: "2026-04-25T18:00:00.000Z" },
  { id: "update-3", taskId: "repair-manual-finder", label: "Reproducer shipped ahead of limit", status: "shipped", summary: "The public reproducer flow launched early after minimal failing cases cleared the release bar.", artifact: "Regression reproducer release", evidenceNote: "Failing tests, environment notes, and maintainer review are archived.", createdAt: "2026-04-23T09:00:00.000Z" },
  { id: "update-4", taskId: "benefit-appeal-packet-helper", label: "Requirement bundle staged", status: "planned", summary: "The first grant and IRB requirement bundle is staged pending pilot sign-off and citation freshness review.", artifact: "Requirement map preview", evidenceNote: "Citations are staged but not yet public.", createdAt: "2026-04-25T16:00:00.000Z" },
  { id: "update-5", taskId: "local-air-quality-briefing", label: "District source layer added", status: "on-track", summary: "The briefing now carries district-specific school notices alongside public sensor readings and clinic guidance.", artifact: "District notice integration", evidenceNote: "Source links and timestamps are preserved per region.", createdAt: "2026-04-24T12:30:00.000Z" },
  { id: "update-6", taskId: "open-source-security-regression-watch", label: "One advisory held for embargo review", status: "at-risk", summary: "A reproducible regression was found, but publication remains paused while maintainers handle embargo timing.", artifact: "Held advisory packet", evidenceNote: "The replay bundle exists but sensitive detail stays private until the gate clears.", createdAt: "2026-04-25T13:00:00.000Z" },
  { id: "update-7", taskId: "rare-disease-evidence-atlas", label: "Expert correction round merged", status: "on-track", summary: "Specialist reviewers kept the contradiction log intact and requested clearer uncertainty labels on two clusters.", artifact: "Correction pass one", evidenceNote: "Reviewer notes and source diffs are attached to the atlas history.", createdAt: "2026-04-24T14:15:00.000Z" },
  { id: "update-8", taskId: "clinic-follow-up-question-drafter", label: "Pilot shipped with limited scope", status: "partial", summary: "Clinicians found the drafting useful for note triage, but broader automation was intentionally deferred after the compute window ended.", artifact: "Pilot retrospective", evidenceNote: "Accepted, edited, and rejected outputs remain available for audit.", createdAt: "2026-04-23T17:30:00.000Z" },
  { id: "update-9", taskId: "museum-oral-history-indexer", label: "Archive rights review underway", status: "planned", summary: "Consent forms, speaker restrictions, and image-use notes are being normalized before ingestion begins.", artifact: "Rights review workbook", evidenceNote: "Archive staff comments are preserved in the staging packet.", createdAt: "2026-04-25T10:30:00.000Z" },
  { id: "update-10", taskId: "public-domain-performance-studio", label: "Creative pilot recruited", status: "planned", summary: "Two school and theater groups volunteered to test the rights-safe rehearsal packet flow if the Ken reaches the days lane.", artifact: "Pilot interest log", evidenceNote: "Interested groups are listed in the partner note set.", createdAt: "2026-04-25T09:00:00.000Z" },
];

export const seedCheckpointGates: CheckpointGateRecord[] = [
  { checkpointId: "checkpoint-1", approvalScore: 18, requiredApprovals: 16, releaseStatus: "approved" },
  { checkpointId: "checkpoint-2", approvalScore: 12, requiredApprovals: 16, releaseStatus: "pending" },
  { checkpointId: "checkpoint-3", approvalScore: 0, requiredApprovals: 18, releaseStatus: "pending" },
  { checkpointId: "checkpoint-4", approvalScore: 0, requiredApprovals: 18, releaseStatus: "pending" },
  { checkpointId: "checkpoint-5", approvalScore: 24, requiredApprovals: 22, releaseStatus: "approved" },
  { checkpointId: "checkpoint-6", approvalScore: 16, requiredApprovals: 22, releaseStatus: "pending" },
  { checkpointId: "checkpoint-7", approvalScore: 27, requiredApprovals: 24, releaseStatus: "approved" },
  { checkpointId: "checkpoint-8", approvalScore: 14, requiredApprovals: 24, releaseStatus: "pending" },
  { checkpointId: "checkpoint-9", approvalScore: 25, requiredApprovals: 24, releaseStatus: "approved" },
  { checkpointId: "checkpoint-10", approvalScore: 15, requiredApprovals: 24, releaseStatus: "pending" },
  { checkpointId: "checkpoint-11", approvalScore: 0, requiredApprovals: 12, releaseStatus: "pending" },
  { checkpointId: "checkpoint-12", approvalScore: 10, requiredApprovals: 8, releaseStatus: "approved" },
  { checkpointId: "checkpoint-13", approvalScore: 0, requiredApprovals: 8, releaseStatus: "pending" },
];

export const seedComments: CommentRecord[] = [
  { id: "comment-1", taskId: "home-energy-upgrade-companion", profileId: "noor-haddad", parentId: null, body: "This is exactly the kind of Ken that needs sustained compute: the hard part is not extracting one protocol, it is keeping every ambiguity visible until reviewers settle it.", stakeCredits: 3, createdAt: "2026-04-25T11:00:00.000Z" },
  { id: "comment-2", taskId: "home-energy-upgrade-companion", profileId: "maya-chen", parentId: "comment-1", body: "Agreed. I want the source spans and rejected inferences to stay first-class so a lab can audit why a step was not promoted into the checklist.", stakeCredits: 2, createdAt: "2026-04-25T11:06:00.000Z" },
  { id: "comment-3", taskId: "benefit-appeal-packet-helper", profileId: "jordan-miles", parentId: null, body: "The useful version is not a grant-writing robot. It should surface deadlines, attachments, and IRB dependencies that humans can verify faster.", stakeCredits: 3, createdAt: "2026-04-25T11:14:00.000Z" },
  { id: "comment-4", taskId: "benefit-appeal-packet-helper", profileId: "rafael-ortiz", parentId: "comment-3", body: "The public demo should also show uncertainty. If a requirement is ambiguous, the board should see that instead of a polished but unsupported answer.", stakeCredits: 2, createdAt: "2026-04-25T11:20:00.000Z" },
  { id: "comment-5", taskId: "local-air-quality-briefing", profileId: "priya-singh", parentId: null, body: "Freshness is the product here. Schools and clinics need a source-linked morning brief with timestamps, not another static dashboard nobody checks during a smoke event.", stakeCredits: 3, createdAt: "2026-04-25T11:30:00.000Z" },
  { id: "comment-6", taskId: "open-source-security-regression-watch", profileId: "maya-chen", parentId: null, body: "If the replay bundles stay precise, this saves maintainers from rediscovering the same regression under three different issue titles.", stakeCredits: 3, createdAt: "2026-04-25T11:40:00.000Z" },
  { id: "comment-7", taskId: "rare-disease-evidence-atlas", profileId: "noor-haddad", parentId: null, body: "The point is continuity. Patient groups can sometimes fund a literature scan, but rarely a living contradiction map that keeps improving.", stakeCredits: 3, createdAt: "2026-04-25T11:48:00.000Z" },
  { id: "comment-8", taskId: "clinic-follow-up-question-drafter", profileId: "priya-singh", parentId: null, body: "The partial result is still valuable. It saved clinicians review time, and stopping at the compute limit made the boundary more credible.", stakeCredits: 2, createdAt: "2026-04-25T11:56:00.000Z" },
  { id: "comment-9", taskId: "museum-oral-history-indexer", profileId: "aiko-tanaka", parentId: null, body: "Small archives should not need a custom software budget just to make local history searchable, rights-aware, and teachable.", stakeCredits: 2, createdAt: "2026-04-25T12:05:00.000Z" },
  { id: "comment-10", taskId: "autonomous-phishing-lure-optimizer", profileId: "elena-petrov", parentId: null, body: "Keeping blocked Kens visible matters because it shows the safety boundary in public instead of pretending harmful demand does not exist.", stakeCredits: 1, createdAt: "2026-04-25T12:12:00.000Z" },
];

export const seedCommentVotes: CommentVoteRecord[] = [
  { id: "comment-vote-1", commentId: "comment-1", profileId: "maya-chen", value: 1, updatedAt: "2026-04-25T12:30:00.000Z" },
  { id: "comment-vote-2", commentId: "comment-1", profileId: "priya-singh", value: 1, updatedAt: "2026-04-25T12:31:00.000Z" },
  { id: "comment-vote-3", commentId: "comment-2", profileId: "noor-haddad", value: 1, updatedAt: "2026-04-25T12:33:00.000Z" },
  { id: "comment-vote-4", commentId: "comment-3", profileId: "priya-singh", value: 1, updatedAt: "2026-04-25T12:35:00.000Z" },
  { id: "comment-vote-5", commentId: "comment-3", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-04-25T12:36:00.000Z" },
  { id: "comment-vote-6", commentId: "comment-4", profileId: "jordan-miles", value: 1, updatedAt: "2026-04-25T12:38:00.000Z" },
  { id: "comment-vote-7", commentId: "comment-5", profileId: "jordan-miles", value: 1, updatedAt: "2026-04-25T12:41:00.000Z" },
  { id: "comment-vote-8", commentId: "comment-5", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-04-25T12:42:00.000Z" },
  { id: "comment-vote-9", commentId: "comment-6", profileId: "elena-petrov", value: 1, updatedAt: "2026-04-25T12:45:00.000Z" },
  { id: "comment-vote-10", commentId: "comment-7", profileId: "priya-singh", value: 1, updatedAt: "2026-04-25T12:48:00.000Z" },
  { id: "comment-vote-11", commentId: "comment-7", profileId: "maya-chen", value: 1, updatedAt: "2026-04-25T12:49:00.000Z" },
  { id: "comment-vote-12", commentId: "comment-8", profileId: "noor-haddad", value: 1, updatedAt: "2026-04-25T12:51:00.000Z" },
  { id: "comment-vote-13", commentId: "comment-9", profileId: "rafael-ortiz", value: 1, updatedAt: "2026-04-25T12:54:00.000Z" },
  { id: "comment-vote-14", commentId: "comment-10", profileId: "maya-chen", value: 1, updatedAt: "2026-04-25T12:57:00.000Z" },
];

export const seedRevenueStreams: RevenueStreamRecord[] = [
  {
    id: "revenue-1",
    slug: "hosted-workflows",
    name: "Supported workflow subscriptions",
    engine: "enterprise",
    description: "Paid support, uptime, reporting, and connectors for proven Kens after they already demonstrated public value.",
    pricingModel: "Annual subscriptions plus onboarding",
    status: "live",
    monthlyRevenueUsd: 64000,
    grossMargin: 0.8,
    treasurySharePercent: 80,
    founderSharePercent: 20,
    publicBenefitCovenant: "Each paid deployment funds shared compute without changing board ranking, voice allocation, or checkpoint approval.",
    openDeliverableBoundary: "Public methods, evidence formats, non-sensitive outputs, and checkpoint summaries remain readable; paid layers cover support and operations.",
    contributorDividendPercent: 0,
    requiresContributorConsent: false,
  },
  {
    id: "revenue-2",
    slug: "correction-licensing",
    name: "Screened evaluation licensing",
    engine: "data-licensing",
    description: "Consented correction traces and evaluation records licensed for audit, benchmarking, and model-improvement work.",
    pricingModel: "Quarterly licensing agreements",
    status: "pilot",
    monthlyRevenueUsd: 26000,
    grossMargin: 0.77,
    treasurySharePercent: 80,
    founderSharePercent: 20,
    publicBenefitCovenant: "Licensing never changes board ranking; proceeds flow back into compute, review, and contributor credit systems.",
    openDeliverableBoundary: "Only screened records from consenting contributors are eligible for external licensing; public audit trails remain separately visible.",
    contributorDividendPercent: 10,
    requiresContributorConsent: true,
  },
  {
    id: "revenue-3",
    slug: "off-peak-routing",
    name: "Managed compute routing",
    engine: "compute-arbitrage",
    description: "Compatible private jobs routed through lower-cost windows, with surplus returned to the public compute treasury.",
    pricingModel: "Usage-based orchestration margin",
    status: "live",
    monthlyRevenueUsd: 21000,
    grossMargin: 0.74,
    treasurySharePercent: 80,
    founderSharePercent: 20,
    publicBenefitCovenant: "Private routing stays firewalled from public allocation and only contributes funding supply, never influence.",
    openDeliverableBoundary: "Customers pay for routing, reporting, and support while the public board keeps its own allocation logic.",
    contributorDividendPercent: 0,
    requiresContributorConsent: false,
  },
  {
    id: "revenue-4",
    slug: "restricted-civic-sponsorships",
    name: "Restricted sponsorship pools",
    engine: "sponsorship",
    description: "Mission-aligned contributions reserved for a category, Ken, or safety reserve without buying rank or release control.",
    pricingModel: "Restricted sponsorship pools",
    status: "planned",
    monthlyRevenueUsd: 12000,
    grossMargin: 0.55,
    treasurySharePercent: 90,
    founderSharePercent: 10,
    publicBenefitCovenant: "Sponsors can fund a lane, category, or Ken but cannot buy ranking, voice, or release approval.",
    openDeliverableBoundary: "Sponsored work keeps the same public checkpoints, blocked-work visibility, and open audit expectations as every other Ken.",
    contributorDividendPercent: 0,
    requiresContributorConsent: false,
  },
];

export const seedTreasuryEntries: TreasuryEntryRecord[] = [
  { id: "treasury-0", streamId: null, title: "Demo runway reserve", description: "Sandbox capital used to demonstrate the full treasury and release flow before all external funding is live.", bucket: "compute-treasury", direction: "inflow", amountUsd: 24000, fundingState: "simulated", restrictionMode: "unrestricted", restrictionScope: "general", restrictionTargetId: null, restrictionTargetLabel: "Demo runway", createdAt: "2026-04-20T09:00:00.000Z" },
  { id: "treasury-1", streamId: "revenue-1", title: "Supported workflow routing", description: "April subscription revenue routed into the compute treasury under the public split.", bucket: "compute-treasury", direction: "inflow", amountUsd: 51200, fundingState: "committed", restrictionMode: "unrestricted", restrictionScope: "general", restrictionTargetId: null, restrictionTargetLabel: "Shared compute treasury", createdAt: "2026-04-21T09:00:00.000Z" },
  { id: "treasury-2", streamId: "revenue-2", title: "Correction licensing routing", description: "Pilot licensing proceeds from screened correction and checkpoint data.", bucket: "compute-treasury", direction: "inflow", amountUsd: 20800, fundingState: "committed", restrictionMode: "unrestricted", restrictionScope: "general", restrictionTargetId: null, restrictionTargetLabel: "Shared compute treasury", createdAt: "2026-04-22T09:00:00.000Z" },
  { id: "treasury-3", streamId: "revenue-3", title: "Off-peak routing surplus", description: "Margin captured from neutral compute routing for compatible private workloads.", bucket: "compute-treasury", direction: "inflow", amountUsd: 16800, fundingState: "committed", restrictionMode: "unrestricted", restrictionScope: "general", restrictionTargetId: null, restrictionTargetLabel: "Shared compute treasury", createdAt: "2026-04-23T09:00:00.000Z" },
  { id: "treasury-4", streamId: "revenue-4", title: "Restricted public-interest pool", description: "Restricted inflow reserved for public-interest Kens, including smoke briefings and public-records review.", bucket: "compute-treasury", direction: "inflow", amountUsd: 9600, fundingState: "committed", restrictionMode: "restricted", restrictionScope: "category", restrictionTargetId: "public-interest", restrictionTargetLabel: "Public Interest", createdAt: "2026-04-24T09:00:00.000Z" },
  { id: "treasury-5", streamId: null, title: "Month-lane compute allocation", description: "Capital released to month-scale Kens after public checkpoint approval.", bucket: "compute-treasury", direction: "outflow", amountUsd: 56000, fundingState: "committed", restrictionMode: "unrestricted", restrictionScope: "general", restrictionTargetId: null, restrictionTargetLabel: "Month lane", createdAt: "2026-04-24T12:00:00.000Z" },
  { id: "treasury-6", streamId: null, title: "Week-lane compute allocation", description: "Capital released to active and scheduled week-scale Kens across science, security, and cultural lanes.", bucket: "compute-treasury", direction: "outflow", amountUsd: 17000, fundingState: "committed", restrictionMode: "unrestricted", restrictionScope: "general", restrictionTargetId: null, restrictionTargetLabel: "Week lane", createdAt: "2026-04-25T09:00:00.000Z" },
  { id: "treasury-7a", streamId: null, title: "Safety reserve transfer", description: "Operating transfer into the safety and audit reserve before additional month-lane launches.", bucket: "compute-treasury", direction: "outflow", amountUsd: 8000, fundingState: "committed", restrictionMode: "restricted", restrictionScope: "safety-reserve", restrictionTargetId: "safety-reserve", restrictionTargetLabel: "Safety and audit reserve", createdAt: "2026-04-25T09:30:00.000Z" },
  { id: "treasury-7b", streamId: null, title: "Safety and audit reserve", description: "Reserved capital for attestation review, checkpoint moderation, incident response, and external audit.", bucket: "safety-reserve", direction: "inflow", amountUsd: 8000, fundingState: "committed", restrictionMode: "restricted", restrictionScope: "safety-reserve", restrictionTargetId: "safety-reserve", restrictionTargetLabel: "Safety and audit reserve", createdAt: "2026-04-25T09:31:00.000Z" },
  { id: "treasury-8", streamId: null, title: "Founder operations transfer", description: "Founder operations support routed under the public reporting rule.", bucket: "founder-ops", direction: "inflow", amountUsd: 15700, fundingState: "committed", restrictionMode: "unrestricted", restrictionScope: "general", restrictionTargetId: null, restrictionTargetLabel: "Founder operations", createdAt: "2026-04-25T10:00:00.000Z" },
];

export const seedSponsorshipCommitments: SponsorshipCommitmentRecord[] = [
  {
    id: "sponsorship-1",
    sponsorName: "North Coast Clean Air Fund",
    sponsorType: "foundation",
    sponsorContact: "partners@northcoastair.example",
    note: "Preparing a seasonal sponsorship that can only fund public-interest Kens and open deliverables.",
    amountUsd: 18000,
    fundingState: "projected",
    status: "intake",
    restrictionScope: "category",
    restrictionTargetId: "public-interest",
    restrictionTargetLabel: "Public Interest",
    checkoutSessionId: null,
    createdAt: "2026-04-25T10:00:00.000Z",
    updatedAt: "2026-04-25T10:00:00.000Z",
    paidAt: null,
  },
  {
    id: "sponsorship-2",
    sponsorName: "Cedar Library Network",
    sponsorType: "nonprofit",
    sponsorContact: "innovation@cedarlibraries.example",
    note: "Demo commitment reserved for a cultural Ken so the board can show a full release path before live billing is enabled.",
    amountUsd: 6000,
    fundingState: "simulated",
    status: "paid",
    restrictionScope: "ken",
    restrictionTargetId: "museum-oral-history-indexer",
    restrictionTargetLabel: "Oral History Multimodal Index",
    checkoutSessionId: null,
    createdAt: "2026-04-25T11:45:00.000Z",
    updatedAt: "2026-04-25T11:45:00.000Z",
    paidAt: "2026-04-25T11:45:00.000Z",
  },
];
